	MSG	<pepper OTHER [St][ar] [Fo]x, [we] [ha][ve] [an] [em][er][ge]ncy!>
	MSG	<pepper OTHER [An][dr]o[ss] [is] [al]i[ve]...>
	MSG	<pepper OTHER ...[an]d [he]'s la[un][ch][ed] [an] [at][ta][ck] [ag]a[in][st] [Co][rn][er][ia]!>
	MSG	<pepper OTHER [en][em]y [fo]r[ce]s [ha][ve] [so]r[ti][ed] [fr][om] [An][dr]o[ss]' mo[th][er][sh][ip]s>
	MSG	<pepper OTHER [an]d [ca][rr][ie]rs, [an]d [ar]e [he]ad[in]g [to][wa]rds [Co][rn][er][ia].>
	MSG	<pepper OTHER [Th][ey]'[ve] [al][so] built [ba][se]s [on] [se][ve]ral [pl][an][et]s,>
	MSG	<pepper OTHER [an]d [ar]e [fi][ri]ng IPBMs [at] [Co][rn][er][ia].>
	MSG	<pepper OTHER [Yo][ur] [he]lp [is] cruc[ia]l!>
	MSG	<pepper OTHER [Co][rn][er][ia] [ca]n [ta][ke] [so][me] h[it]s,>
	MSG	<pepper OTHER but [wi][th] ex[ce][ss]i[ve] [da][ma][ge], [we] [wi][ll] [fa][ll]!>
	MSG	<pepper OTHER Prote[ct] [Co][rn][er][ia], [an]d [wi]pe [ou]t [An][dr]o[ss]' a[rm]y!>
	MSG	<pepper OTHER [We]'[re] c[ou]n[ti]ng [on] [yo]u, [St][ar] [Fo]x!>
	MSG	<pepper OTHER De[st]roy [th]e [ba][se] [fr][om] [th]e [in][si][de]!>
	MSG	<pepper OTHER At[ta][ck] [th]e [ca][rr][ie]r [an]d [de][st]roy [it]s  co[re]!>
	MSG	<pepper down [Co][rn][er][ia] [is] [ta]k[in]g [da][ma][ge]!>
	MSG	<pepper down [Co][rn][er][ia] [is] [be][in]g [at][ta][ck][ed]...!>
	MSG	<pepper down [Th][er]e's [no] [ti][me]! H[ur]ry...!>
	MSG	<pepper down Mi[ss]i[le]s...! Wh[at] [ar]e [yo]u [do][in]g?!>
	MSG	<pepper down Indu[st][ri][al] [bl]ocks [da][ma][ge]d [by] [Pl][an][et] C[an]n[on] [fi][re]!>
	MSG	<pepper OTHER Li[be]r[at]e [th]e [pl][an][et]s [of] [th]e Lyl[at] sy[st][em]!>
	MSG	<pepper OTHER [Th]e Mo[th][er][sh][ip] [ca]n w[ar]p [to] [pl][an][et]s [wi][th][ou]t [en][em]y [ba][se]s.>
	MSG	<pepper OTHER Choo[se] [wh][er]e [th]e Ar[wi]ng [wi]ll [be] [de][pl]oy[ed] [wi][th] [(B)].>
	MSG	<ANDROSS OTHER I [ha][ve] [re][tu][rn][ed] [to] [ta][ke] my [re][ve]n[ge]!>
	MSG	<andross help [Co][rn][er][ia]n scum!>
	MSG	<andross down [Yo]u [wi][ll] [so][on] [bo]w [be][fo][re] [me]!>
	MSG	<FOX OTHER [Yo]u [ca]n [bo]o[st] [wi][th] [(Y)]!>
	MSG	<FALCO OTHER H[it] [(Y)] [to] ac[ce][le]r[at]e!.>
	MSG	<PEPPY OTHER [(Y)], [le]ts [yo]u [us]e [th]e [bo]o[st]!>
	MSG	<SLIPPY OTHER Pre[ss] [(Y)] [fo]r a [sp]e[ed] [bo]o[st], [ri][bb][it]!>
	MSG	<GIRL1 OTHER [Yo]u [ca]n [bo]o[st] [wh]i[le] ho[ld][in]g [(Y)]!>
	MSG	<GIRL2 OTHER P[re][ss] [(Y)] [to] f[ly] [us][in]g [th]e [bo]o[st]!>
	MSG	<FOX OTHER P[ur][su]e [th][em] [wi][th] [th]e [(Y)] [bo]o[st]!>
	MSG	<FALCO OTHER D[on]['t] [do]ze [of]f! U[se] [th]e [(Y)] [bo]o[st]!>
	MSG	<PEPPY OTHER [Th][ey]'[re] [ge][tt][in]g [aw][ay]! [bo]o[st] [wi][th] [(Y)]!>
	MSG	<SLIPPY OTHER [Th][ey]'[re] [ge][tt][in]g [aw][ay], [ri][bb][it]! U[se] [(Y)] [to] [bo]o[st]!>
	MSG	<GIRL1 OTHER [Th][ey]'[re] [ge][tt][in]g [aw][ay]! C[ha][se] [wi][th] [th]e [(Y)] [bo]o[st]!>
	MSG	<GIRL2 OTHER Gi[ve] C[ha][se] [wi][th] [th]e [(Y)] [bo]o[st]!>
	MSG	<FOX OTHER [Co][rn][er][ia]'s in [da]ng[er]! L[et]'s [re][tr]e[at] [wi][th]  [(ST][NOSP][AR][NOSP][T)]!>
	MSG	<FALCO OTHER T[ch]! ...[le]t's [go] [he]lp [th][em] [wi][th] [(ST][NOSP][AR][NOSP][T)]!>
	MSG	<PEPPY OTHER L[et]'s [he]ad [fo]r [Co][rn][er][ia]! U[se] [(ST][NOSP][AR][NOSP][T)] [to] pu[ll] [ou]t!>
	MSG	<SLIPPY OTHER Got[ta] [sa][ve] [Co][rn][er][ia]! L[et]'s [go] [ba][ck] [wi][th] [(ST][NOSP][AR][NOSP][T)].>
	MSG	<GIRL1 OTHER T[ha]t's [no]t [go][od]! L[et]'s scr[am] [wi][th] [(ST][NOSP][AR][NOSP][T)]!>
	MSG	<GIRL2 OTHER No...! L[et]'s [go] [wi][th] [(ST][NOSP][AR][NOSP][T)]!>
	MSG	<FOX OTHER [Th][er]e's [no] [ti][me]! H[it] [(ST][NOSP][AR][NOSP][T)].>
	MSG	<FALCO OTHER [Th][is] [is] [ba]d! H[it] [(ST][NOSP][AR][NOSP][T)] [to] [go]!>
	MSG	<PEPPY OTHER Not [go][od]! U[se] [(ST][NOSP][AR][NOSP][T)] [to] [le]a[ve]!>
	MSG	<SLIPPY OTHER [We]'[re] [in] [tr][ou][bl]e! R[et][re][at] [wi][th] [(ST][NOSP][AR][NOSP][T)]!>
	MSG	<GIRL1 OTHER L[et]'s gi[ve] [up] [he][re] [fo]r [no]w! P[us]h [(ST][NOSP][AR][NOSP][T)]!>
	MSG	<GIRL2 OTHER Ti[me]'s [up]! [We]'[ll] lo[se] [if] [yo]u [do]n['t] h[it] [(ST][NOSP][AR][NOSP][T)] [no]w!>
	MSG	<FOX OTHER Y[ou]'[re] r[et][re][at][in]g [fr][om] [th]e b[at]t[le]. Go [ba][ck]!>
	MSG	<FALCO OTHER [Th]e b[at]t[le]'s [ov][er] [th][er]e!>
	MSG	<PEPPY OTHER [Th][er]e's [no][th][in]g [he][re]! Go [ba][ck]!>
	MSG	<SLIPPY OTHER Lo[st]? It's [th][is] [wa]y, [ri][bb][it]!>
	MSG	<GIRL1 OTHER I'm [go][in]g [ba][ck]! Th[is] [wa]y!>
	MSG	<GIRL2 OTHER No[th][in]g [he][re]. L[et]'s [go] [ba][ck]... >
	MSG	<FOX OTHER Y[ou] c[an] [tr][an]s[fo][rm] [wi][th] [(SE][NOSP][LE][NOSP][CT)]!>
	MSG	<FALCO OTHER [(SE][NOSP][LE][NOSP][CT)] [tr][an]s[fo][rm]s [yo][ur] Ar[wi]ng!>
	MSG	<PEPPY OTHER Y[ou] c[an] [ch][an][ge] [fo][rm] [if] y[ou] h[it] [(SE][NOSP][LE][NOSP][CT)].>
	MSG	<SLIPPY OTHER [(SE][NOSP][LE][NOSP][CT)] [tr][an]s[fo][rm]s [yo][ur] Ar[wi]ng, [ri][bb][it]!>
	MSG	<GIRL1 OTHER [If] [yo]u w[an]t [to] [tr][an]s[fo][rm], h[it] [(SE][NOSP][LE][NOSP][CT)]!>
	MSG	<GIRL2 OTHER Wh[en] [yo]u h[it] [(SE][NOSP][LE][NOSP][CT)], [yo][ur] Ar[wi]ng [wi][ll] [tr][an]s[fo][rm]!>
	MSG	<FOX OTHER Avoid [th]e m[ag][ma]!>
	MSG	<FALCO OTHER D[on]['t] co[me] cry[in]g [if] [yo]u g[et] bu[rn][ed]!>
	MSG	<PEPPY OTHER [If] [yo]u l[an]d [on] m[ag][ma], [yo]u'[ll] [ta][ke] [da][ma][ge]!>
	MSG	<SLIPPY OTHER My [bo]dy's [al]l [dr][ie]d [ou]t! Hot, hot!>
	MSG	<GIRL1 OTHER The Ar[wi]ngs c[an]['t] [wi][th][st][an]d m[ag][ma]!>
	MSG	<GIRL2 OTHER Be [ca][re]f[ul] [of] [th]e m[ag][ma]!>
	MSG	<FOX OTHER Look f[or] [th]e sw[it][ch] [to] op[en] [th]e [ga]te!>
	MSG	<FALCO OTHER F[in]d [th]e sw[it][ch] [to] op[en] [th]e [en][tr][an][ce]!>
	MSG	<PEPPY OTHER [We]'[re] [ge][tt][in]g [no][wh][er]e. Go[tt]a [ge]t [in][si][de]!>
	MSG	<SLIPPY OTHER Look f[or] [th]e [en][tr][an][ce] sw[it][ch], [ri][bb][it]!>
	MSG	<GIRL1 OTHER [Th][is] [is] [po][in]t[le][ss]! [We] [ha][ve] [to] [ge]t [in][si][de]!>
	MSG	<GIRL2 OTHER [Th][er]e [mu][st] [be] a sw[it][ch] [so][me]w[he][re]!>
	MSG	<FOX OTHER [Th][ey]'[ve] put [up] a [ba][rr][ie]r!>
	MSG	<FALCO OTHER [We] [ha][ve] [to] [de][st]roy [th]e [ba][rr][ie]r g[en][er][at][or]!>
	MSG	<PEPPY OTHER [If] [we] [do]n['t] [de][st]roy [th]e [ba][rr][ie]r [fi]r[st]... >
	MSG	<SLIPPY OTHER De[st]roy [th]e [ba][rr][ie]r g[en][er][at][or], [ri][bb][it]!>
	MSG	<GIRL1 OTHER Go[tt]a [ge]t [th]r[ou]gh [th]e [ba][rr][ie]r!>
	MSG	<GIRL2 OTHER De[st]roy [th]e [ba][rr][ie]r's g[en][er][at][or]!>
	MSG	<pepper help A [ne]w squa[dr][on] [ha]s [so]rt[ie]d!>
	MSG	<pepper help [An] IPBM [ha]s [be][en] [fi][re]d at [Co][rn][er][ia]!>
	MSG	<pepper help A [ne]w [en][em]y [ca][rr][ie]r [ha]s appea[re]d!>
	MSG	<pepper OTHER Be aw[ar]e [of] [Co][rn][er][ia]'s c[on]d[it]i[on]!>
	MSG	<FOX OTHER >
	MSG	<ANDROSS OTHER I'm g[on]na gi[ve] [yo]u p[un]ks a [go][od] [th]r[as]h[in]g!>
	MSG	<pepper OTHER [We][ll] [do][ne]! [Th]at [ou]ght [to] s[to]p [th]e [mi][ss]i[le] [at][ta][ck]s.>
	MSG	<ANDROSS help Ge[tt][in]g [in] my [wa]y [ag]a[in]... >
	MSG	<ANDROSS down G[wa]aargh! Wh[at] [is] [he] DOING?!>
	MSG	<pepper OTHER Go[od]! [Th][at] [ou]ght [to] sl[ow] [th][em] d[ow]n.>
	MSG	<FOX OTHER C[on]t[in]ue [as] [wi]ngm[an]?>
	MSG	<FOX OTHER Yes>
	MSG	<FOX OTHER No>
	MSG	<pepper OTHER [Th][is] [is] o[ur] S[at]e[ll][it]e Def[en][se] Sy[st][em].>
	MSG	<pepper OTHER [Th]e s[at]e[ll][it]e sy[st][em] h[as] [be][en] [ca]pt[ur][ed]! Rec[ov][er] [it]!>
	MSG	<FOX OTHER MISSION>
	MSG	<FOX OTHER RECORD>
	MSG	<FOX OTHER TEST>
	MSG	<FOX OTHER TRAINING>
	MSG	<FOX OTHER CONFIG>
	MSG	<FOX OTHER STEREO>
	MSG	<FOX OTHER MONO>
	MSG	<FOX OTHER NORMAL>
	MSG	<FOX OTHER HARD>
	MSG	<FOX OTHER EXPERT>
	MSG	<FOX OTHER M[ov]e?                              Yes                  No>
	MSG	<FOX OTHER De[pl]oy [th]e Mo[th][er][sh][ip].>
	MSG	<pepper OTHER Go[od] w[or]k!>
	MSG	<FOX OTHER [RARR]>
	MSG	<pepper OTHER R[et][ur]n [to] [th]e Mo[th][er][sh][ip] [to] [re][st]o[re] [yo][ur] [sh][ie][ld]s.>
	MSG	<pepper down G[wa]aaaaaah! It's [al]l [ov][er]!>
	MSG	<ANDROSS OTHER Looks li[ke] [so][me] r[at]s are sl[ip]p[in]g [th]r[ou]gh... Heh...>
	MSG	<ANDROSS help I'[ll] [go] e[as]y [on] y[ou]! Ga[ha][ha][ha]!>
	MSG	<ANDROSS OTHER Ga[ha][ha][ha]! H[ow] [en]t[er][ta][in][in]g!>
	MSG	<ANDROSS down La[un][ch] IPBMs [at] [Co][rn][er][ia]!>
	MSG	<ANDROSS help [Th][ey]'[re] [in] [th]e [Pl][an][et] C[an]n[on]'s r[an][ge]! Ga[ha][ha]!>
	MSG	<ANDROSS down Fi[re] [th]e [Pl][an][et] C[an]n[on]!>
	MSG	<ANDROSS OTHER I'm ju[st] [ge][tt][in]g [st][ar]t[ed]!>
	MSG	<ANDROSS help Ho ho, d[on]'t g[et] [to]o co[ck]y...>
	MSG	<ANDROSS down [Pl][ay][ti][me]'s [ov][er]! Cr[us]h [th][em]!>
	MSG	<ANDROSS down Imp[re][ss]i[ve] [sh][ow]! L[et] [me] [th][an]k y[ou]...>
	MSG	<ANDROSS help Head [fo]r [Co][rn][er][ia], [an]d [re]ady [th]e [Pl][an][et] C[an]n[on]!>
	MSG	<FOX OTHER You can [bo]o[st] [wi][th] [(X)]!>
	MSG	<FALCO OTHER [Th]e Ar[wi]ng's [bo]o[st] is [(X)]!>
	MSG	<PEPPY OTHER Y[ou]'[ll] ac[ce][le]r[at]e [wh]i[le] p[re][ss][in]g [(X)]!>
	MSG	<SLIPPY OTHER Boo[st] [wh]i[le] p[re][ss][in]g [(X)], [ri][bb][it]!>
	MSG	<GIRL1 OTHER Y[ou] c[an] [bo]o[st] [wh]i[le] p[re][ss][in]g [(X)]!>
	MSG	<GIRL2 OTHER Y[ou] f[ly] fa[st][er] [wh]i[le] p[re][ss][in]g [(X)]!>
	MSG	<FOX OTHER P[ur][su]e [wi][th] [th]e [(X)] [bo]o[st]!>
	MSG	<FALCO OTHER Sl[ow][po]ke! U[se] [th]e [(X)] [bo]o[st]!>
	MSG	<PEPPY OTHER U[se] [th]e [(X)] [bo]o[st] [to] [ca]t[ch] [up]!>
	MSG	<SLIPPY OTHER [Th][ey]'[re] [ge][tt][in]g [aw][ay]! ac[ce][le]r[at]e [wi][th] [(X)]-c[rr]roak!>
	MSG	<GIRL1 OTHER C[ha][se] [th][em] [us][in]g [th]e [(X)] [bo]o[st]!>
	MSG	<GIRL2 OTHER Gi[ve] [ch]a[se] [wi][th] [th]e [(X)] [bo]o[st]!>
	MSG	<ANDROSS OTHER He[he][he]... Y[ou]'[ve] [go]t [sp]ir[it]!>
	MSG	<pepper help Caught [th]e [Pl][an][et] C[an]n[on]'s En[er]gy Ch[ar][ge]!>
	MSG	<pepper OTHER T[he] [Pl][an][et] C[an]n[on] [is] [ch][ar]g[in]g! Ta[ke] [it] [do][wn]!>
	MSG	<ANDROSS OTHER Ad[mi]ra[bl]e, [St][ar] [Fo]x!>
	MSG	<ANDROSS OTHER Y[ou]'[ve] [go][tt][en] [be][tt][er], [St][ar] [Fo]x.>
	MSG	<ANDROSS OTHER Y[ou]'[ve] [fi]na[ll]y co[me] [th][is] f[ar]... >
	MSG	<ANDROSS help Imp[re][ss]i[ve]! But [yo]u d[ie] [he][re]!>
	MSG	<ANDROSS help Pepp[er]'s [do]gs!>
	MSG	<ANDROSS help Y[ou]'[re] ALWAYS [ge][tt][in]g [in] my [wa]y!! >
	MSG	<ANDROSS down Suff[er]!!>
	MSG	<ANDROSS down Ti[me] f[or] my [re][ve]n[ge]!>
	MSG	<ANDROSS down D[on]['t] w[or]ry, I'[ll] [go] e[as]y!>
	MSG	<FOX OTHER [Th]e m[is][si][le]s a[re] [fa]ll[in]g!>
	MSG	<FALCO OTHER [Th]o[se] d[am]n m[is][si][le]s...!>
	MSG	<PEPPY OTHER m[is][si][le]s a[re] [fa]ll[in]g on [Co][rn][er][ia]!>
	MSG	<SLIPPY OTHER m[is][si][le]s [dr]opp[in]g to [Co][rn][er][ia], [ri][bb][it]!>
	MSG	<GIRL1 OTHER Eeek! m[is][si][le]s a[re] [fa]ll[in]g on [Co][rn][er][ia]!>
	MSG	<GIRL2 OTHER No! The m[is][si][le]s a[re] [fa]ll[in]g on [Co][rn][er][ia]!>
	MSG	<FOX OTHER G[re][at]! No mo[re] m[is][si][le]s [wi][ll] [be] [fi][re]d [fr][om] [he][re]!>
	MSG	<FALCO OTHER P[ie][ce] [of] cake!>
	MSG	<PEPPY OTHER Al[ri]ght! [Th][at]'s [th][is] [pl][an][et]!>
	MSG	<SLIPPY OTHER Ho[or][ay]! No mo[re] m[is][si][le]s [fr][om] [he][re]!>
	MSG	<GIRL1 OTHER Yeeeeeee[ha]w!>
	MSG	<GIRL2 OTHER O[ur] m[is][si][le] prob[le]ms ju[st] [go]t light[er]!>
	MSG	<FOX OTHER B[at]t[le][sh][ip] [de][st]roy[ed]!>
	MSG	<FALCO OTHER The bigger they are...>
	MSG	<PEPPY OTHER [Th][at]'[ll] [ma]ke [th][in]gs e[as]i[er]!>
	MSG	<SLIPPY OTHER [An] e[as]y [vi]ct[or]y, [ri][bb][it]!>
	MSG	<GIRL1 OTHER Scr[at][ch] [on]e!>
	MSG	<GIRL2 OTHER [Th][at]'[ll] [re]du[ce] their [fo]r[ce]s!>
	MSG	<wolf down Noooo! [St][ar] [Fo]x...!>
	MSG	<chameleon down Gaaah! [Wo][lf], I [le]a[ve] [th]e [re][st] [to] [yo]u!>
	MSG	<pig down Be[at][en] [by] [th]e[se] p[un]ks...! I'[ve] [go][tt][en] r[us]ty...>
	MSG	<monkey down A[rr]ghh! I'[ll] [re][me]mb[er] [th][is]...!>
	MSG	<wolf down I'[ll] p[ay] y[ou] [ba][ck] f[or] [th][is]!>
	MSG	<chameleon OTHER [Th][at]'s f[ar] [en][ou]gh! Le[on] [of] [St][ar] [Wo][lf] [is] [he][re]!>
	MSG	<pig OTHER I'm Pig[ma] [of] [St][ar] [Wo][lf]! P[re]pa[re] y[ou]r[se][lf]!>
	MSG	<monkey OTHER I'm Algy! I w[on]['t] j[us]t [le]t y[ou] [do] [wh][at] y[ou] w[an]t!>
	MSG	<wolf OTHER D[et]es[ta]b[le] p[un]ks!>
	MSG	<chameleon OTHER So [yo]u'[re] [Wo][lf]'s t[ar][ge]ts... Ti[me] [to] d[ie]!>
	MSG	<pig OTHER [An][dr]o[ss] paid [go][od] [ca][sh] f[or] su[ch] [an] e[as]y job!>
	MSG	<monkey OTHER O[ur] [bo][ss] [sa]id y[ou] [we][re] [no][th][in]g [sp]eci[al]!>
	MSG	<wolf OTHER Br[at]s! Ti[me] f[or] p[un][is]hm[en]t!>
	MSG	<pepper OTHER [Th]e s[at]e[ll][it]e sy[st][em] h[as] [be][en] [ca]pt[ur][ed]! Rec[ov][er] [it]!>
	MSG	<wolf OTHER Ti[me] [to] [en]d [ou]r [ri]v[al]ry!>
	MSG	<chameleon OTHER Not [ba]d, [St][ar] [Fo]x! But I w[on]['t] lo[se]!>
	MSG	<pig OTHER [Th][at] w[as] j[us]t [th]e [be]g[in]n[in]g!>
	MSG	<monkey OTHER I w[on]['t] l[et] y[ou] [of]f [so] e[as]y!>
	MSG	<wolf OTHER I, [Wo][lf], w[on]['t] [le]t [yo]u [go] [an]y f[ur][th][er]!>
	MSG	<FOX OTHER P[he]w, [we] did [it]!>
	MSG	<FALCO OTHER Hmph! No big [de][al].. >
	MSG	<PEPPY OTHER A[re] [yo]u ok[ay]? [Th][at] w[as] clo[se]!>
	MSG	<SLIPPY OTHER [Th][at] w[as] a clo[se] [on]e, [ri][bb][it]!>
	MSG	<GIRL1 OTHER T[ou]gh[ie], eh?>
	MSG	<GIRL2 OTHER [he]w, [th][at] w[as] clo[se]!>
	MSG	<FOX special [We]'[re] ok[ay]!>
	MSG	<FALCO special Hmph! [An] e[as]y [vi]ct[or]y!>
	MSG	<PEPPY special No [ne][ed] [to] w[or]ry!>
	MSG	<SLIPPY special My [he][ar]t w[as] p[ou]nd[in]g [to]o, [ri][bb][it]!>
	MSG	<GIRL1 special W[ha]t [ar]e y[ou] [ta]lk[in]g ab[ou]t!? Pah!>
	MSG	<GIRL2 special Huh? I w[as] [to]t[al][ly] com[po]s[ed]!>
	MSG	<pepper OTHER U[se] [th]e Mo[th][er][sh][ip] [to] [re]co[ve]r [an]d w[ar]p.>
	MSG	<pepper down [Th]e s[at]e[ll][it]e [is] [at][ta][ck][in]g [Co][rn][er][ia]! H[ur]ry!>
	MSG	<pepper OTHER [Th]e s[at]e[ll][it]e sy[st][em] [sh]ot d[ow]n [th]e [en][em]y.>
	MSG	<FOX OTHER Tap [(L)] [or] [(R)] t[wi][ce] [to] [ba]r[re]l ro[ll]!>
	MSG	<FALCO OTHER Tap [(L)] [or] [(R)] t[wi][ce] [to] [ba]r[re]l ro[ll]!>
	MSG	<PEPPY OTHER Tap [(L)] [or] [(R)] t[wi][ce]! Ro[ll] [an]d [re]f[le][ct]!>
	MSG	<SLIPPY OTHER Tap [(L)] [or] [(R)] t[wi][ce] [to] [re]f[le][ct] [en][em]y l[as][er]s!>
	MSG	<GIRL1 OTHER Tap [(L)] [or] [(R)] t[wi][ce] [to] ro[ll] [an]d [re]f[le][ct]!>
	MSG	<GIRL2 OTHER Tap [(L)] [or] [(R)] t[wi][ce] [to] [re]f[le][ct] [en][em]y l[as][er]s!>
	MSG	<pepper OTHER I'[ll] ex[pl]a[in] [th]e W[al]k[er]'s c[on][tr]ols.>
	MSG	<pepper OTHER U[se] [DPAD] [to] m[ov]e, [an]d t[ur]n [wi][th] [(L)] [an]d [(R)].>
	MSG	<pepper OTHER You can ac[ce][le]r[at]e by [ta]pp[in]g [DPAD]  t[wi][ce].>
	MSG	<pepper OTHER Jump [wi][th] [(Y)]. [(SE][NOSP][LE][NOSP][CT)] [ch][an][ge]s f[or]ms.>
	MSG	<pepper OTHER U[se] [th]e Ar[wi]ng's [tr][an]s[fo][rm][at]i[on] [wi][se][ly]!>
	MSG	<pepper help [Th]e s[at]e[ll][it]e sy[st][em] h[as] [be][en] [ca]pt[ur][ed]! Rec[ov][er] [it]!>
	MSG	<pepper OTHER Wi[th] [th][is], mo[st] [of] [An][dr]o[ss]' f[or][ce]s [ha][ve] [be][en] s[we]pt a[wa]y.>
	MSG	<pepper OTHER [We]'[ve] [go]t him [ri]ght [wh][er]e [we] w[an]t him!>
	MSG	<pepper OTHER [Yo]u c[an] [ch][an][ge] [to] [yo][ur] [wi]ng[ma]n [if] y[ou] p[re][ss] [(SE][NOSP][LE][NOSP][CT)].>
	MSG	<pepper OTHER Jump [wi][th] [(B)]. [(SE][NOSP][LE][NOSP][CT)] [ch][an][ge]s f[or]ms.>
	MSG	<pepper OTHER Bl[as]t[er] le[ve]l[ed] [up] - [no]w [it] ho[me]s [in]!>
	MSG	<pepper OTHER U[se] [th]e t[ar][ge]t m[ar]k[er] [to] lo[ck] [on], [th][en] fi[re]!>
	MSG	<pepper OTHER A [se]c[re]t [ba][se]... Go [on] [in].>
