	MSG	<PEPPER OTHER Star Fox team-do you read me? I have terrible news.>
	MSG	<PEPPER OTHER Our sworn enemy, the fiend Andross, is alive!>
	MSG	<PEPPER OTHER Even as we speak, he is launching an assault on Corneria.>
	MSG	<PEPPER OTHER The Battle Carriers and attack forces of Andross>
	MSG	<PEPPER OTHER are now advancing on Corneria.>
	MSG	<PEPPER OTHER Enemy bases have been established on overrun planets.>
	MSG	<PEPPER OTHER Planetary missiles will be fired from these enemy bases.>
	MSG	<PEPPER OTHER Once again, we must ask you for your assistance, Star Fox.>
	MSG	<PEPPER OTHER Corneria will survive if it sustains minor damage, but if>
	MSG	<PEPPER OTHER damage reaches [1][0][0] percent, it is all over.>
	MSG	<PEPPER OTHER Engage the forces of Andross while at the same time keeping>
	MSG	<PEPPER OTHER damage to Corneria at the lowest level possible. Good Luck!>
	MSG	<PEPPER OTHER You must infiltrate the enemy base and annihilate it.>
	MSG	<PEPPER OTHER Fly into the Battle Carrier and destroy its energy core.>
	MSG	<PEPPER DOWN Corneria is now under assault!>
	MSG	<PEPPER DOWN Corneria is under direct enemy attack! Help us...>
	MSG	<PEPPER DOWN Enemies attacking Corneria...defenses weakening...>
	MSG	<PEPPER DOWN We have been hit by a planetary missile!>
	MSG	<PEPPER DOWN The Planet Cannon has caused heavy damage here!>
	MSG	<PEPPER OTHER To engage the enemy, land on planets and intercept ships.>
	MSG	<PEPPER OTHER Return to your Mothership to warp to any free planet.>
	MSG	<PEPPER OTHER Select a destination by moving the cursor, then press [(B)].>
	MSG	<ANDROSS OTHER I have returned! I shall make the Cornerians suffer!>
	MSG	<ANDROSS HELP Inhabitants of Corneria-you shall fear my vengeance.>
	MSG	<ANDROSS DOWN I will demonstrate my awesome power on all of Lylat!>
	MSG	<FOX OTHER Don't forget to press [(Y)] to fire your boosters!>
	MSG	<FALCO OTHER Your boosters are activated by pressing [(Y)].>
	MSG	<PEPPY OTHER By pressing [(Y)], you can boost your speed.>
	MSG	<SLIPPY OTHER Fly faster by pressing-ribbit!- [(Y)].>
	MSG	<GIRL1 OTHER If you want to speed up, use [(Y)].>
	MSG	<GIRL2 OTHER Press [(Y)] and you will activate your boosters!>
	MSG	<FOX OTHER Boost your speed and chase down enemies with [(Y)]!>
	MSG	<FALCO OTHER You're flying too slow! Use [(Y)] to speed up.>
	MSG	<PEPPY OTHER We're falling behind. Press [(Y)] to boost speed!>
	MSG	<SLIPPY OTHER They're getting away! Press [(Y)]- rrrribbit!>
	MSG	<GIRL1 OTHER They are escaping! Catch the enemy by pressing [(Y)]!>
	MSG	<GIRL2 OTHER If we don't boost our speed with [(Y)], they'll get away!>
	MSG	<FOX OTHER Corneria is under attack. Hit [STRT]!>
	MSG	<FALCO OTHER Hey! We must get back to Corneria. Press [STRT].>
	MSG	<PEPPY OTHER We have got to return to Corneria! Press [STRT].>
	MSG	<SLIPPY OTHER There's trouble back at Corneria! Press [STRT].>
	MSG	<GIRL1 OTHER Oh, oh! Corneria is in trouble. Press [STRT] to return.>
	MSG	<GIRL2 OTHER Something's up at Corneria. Press [STRT]!>
	MSG	<FOX OTHER This is taking too long. Press [STRT].>
	MSG	<FALCO OTHER Let's get out of here! Press [STRT].>
	MSG	<PEPPY OTHER It's no good! To get out of here, press [STRT].>
	MSG	<SLIPPY OTHER We're wasting time here. Press [STRT]-crrroak!>
	MSG	<GIRL1 OTHER Let's bag this. We took too long. Press [STRT].>
	MSG	<GIRL2 OTHER Time is limited, so let's give this up. Press [STRT].>
	MSG	<FOX OTHER We've left the battlefield. Follow me back!>
	MSG	<FALCO OTHER Our battle site is back there. I'll lead us back.>
	MSG	<PEPPY OTHER Hey, there's no one out here! Follow me back!>
	MSG	<SLIPPY OTHER We may be lost. I think we should go back. Follow me!>
	MSG	<GIRL1 OTHER We should return and attack the enemy. Follow me!>
	MSG	<GIRL2 OTHER There are no enemies out here. Come with me!>
	MSG	<FOX OTHER Remember, press [SLCT] in order to transform.>
	MSG	<FALCO OTHER Press [SLCT] if you want to transform!>
	MSG	<PEPPY OTHER Transform your ship by pressing [SLCT].>
	MSG	<SLIPPY OTHER Don't forget,  press [SLCT] to transform!>
	MSG	<GIRL1 OTHER If you want to transform, press [SLCT]!>
	MSG	<GIRL2 OTHER Press [SLCT], and your ship will transform!>
	MSG	<FOX OTHER Caution! Landing on Magma causes damage.>
	MSG	<FALCO OTHER Don't land! You take damage while on the surface.>
	MSG	<PEPPY OTHER The surface of Magma is burning hot! Don't land.>
	MSG	<SLIPPY OTHER Hot! Hot! Hot! I'm drying out! Don't land-ribbit.>
	MSG	<GIRL1 OTHER The surface is molten! Don't land, okay?>
	MSG	<GIRL2 OTHER Watch it! You take damage if you land on Magma.>
	MSG	<FOX OTHER Attacking from here is no good. Find a switch.>
	MSG	<FALCO OTHER We need to find a switch to open the entrance.>
	MSG	<PEPPY OTHER Attacks from out- side are useless. Activate a switch.>
	MSG	<SLIPPY OTHER We must find a switch that opens an entrance.>
	MSG	<GIRL1 OTHER External attacks are ineffective. Find a switch.>
	MSG	<GIRL2 OTHER There is a switch someplace that opens the entrance.>
	MSG	<FOX OTHER There's a barrier! Knock out the shield generators.>
	MSG	<FALCO OTHER Destroy the shield generators, then start the assault!>
	MSG	<PEPPY OTHER Barrier detected. Find and destroy its power source.>
	MSG	<SLIPPY OTHER A shield generator is here somewhere. Destroy it-ribbit!>
	MSG	<GIRL1 OTHER Cut off power to the barrier, then attack the target.>
	MSG	<GIRL2 OTHER There's a shield! We must destroy its generators.>
	MSG	<PEPPER HELP A Battle Carrier has launched an attack force.>
	MSG	<PEPPER HELP Warning! Planetary missile headed for Corneria!>
	MSG	<PEPPER HELP Emergency! A new Battle Carrier has suddenly appeared.>
	MSG	<PEPPER OTHER Keep an eye on the damage done to Corneria.>
	MSG	<FOX OTHER >
	MSG	<ANDROSS OTHER Show no mercy. Crush them by any means possible.>
	MSG	<PEPPER OTHER Well done! Missile attacks from that planet have ended.>
	MSG	<ANDROSS HELP Star Fox, you mangy cur, how dare you challenge me again?>
	MSG	<ANDROSS DOWN Gwarg!! You pathetic fools are completely worthless!>
	MSG	<PEPPER OTHER Good show! Now we can expect fewer attacks.>
	MSG	<FOX OTHER Continue as wing man?>
	MSG	<FOX OTHER Yes>
	MSG	<FOX OTHER No>
	MSG	<PEPPER OTHER This is our Satellite Defense Platform. It protects Corneria.>
	MSG	<PEPPER OTHER The satellite has been captured! You must liberate it.>
	MSG	<FOX OTHER MISSION>
	MSG	<FOX OTHER RECORD>
	MSG	<FOX OTHER TEST>
	MSG	<FOX OTHER TRAINING>
	MSG	<FOX OTHER CONFIG>
	MSG	<FOX OTHER STEREO>
	MSG	<FOX OTHER MONO>
	MSG	<FOX OTHER NORMAL>
	MSG	<FOX OTHER HARD>
	MSG	<FOX OTHER EXPERT>
	MSG	<FOX OTHER Warp via your Mothership?     Yes                  No>
	MSG	<FOX OTHER Place the cursor on your destination and press [(B)].>
	MSG	<PEPPER OTHER You recaptured the satellite platform. Incredible job!>
	MSG	<FOX OTHER [RARR]>
	MSG	<PEPPER OTHER Your ship's shields are recharged at your Mothership.>
	MSG	<PEPPER DOWN Ayaah! It's all over! Corneria is finished!>
	MSG	<ANDROSS OTHER It appears a puny pet rat is running about...how cute!>
	MSG	<ANDROSS HELP Go play with your pet. Just play nice...Gwah ha ha!>
	MSG	<ANDROSS OTHER Garg gya ha ha! It's no fun when there's no resistance.>
	MSG	<ANDROSS DOWN Launch planetary missiles at Corneria!>
	MSG	<ANDROSS HELP Corneria's within range of the Planet Cannon! Gwarg ha ha!>
	MSG	<ANDROSS DOWN This is meant for you alone. Planet Cannon ...FIRE!!>
	MSG	<ANDROSS OTHER Hmm...you did well, but the real battle hasn't even begun.>
	MSG	<ANDROSS HELP Hyorg! Hyorg! Hyorg! If you think you do well, you are a fool!>
	MSG	<ANDROSS DOWN Play time is over! Destroy the weaklings!>
	MSG	<ANDROSS DOWN You've surprised me. Here is your reward for amusing me.>
	MSG	<ANDROSS HELP Battle Carriers! On to Corneria! Prepare the Planet Cannon!>
	MSG	<FOX OTHER Boost your speed by pressing [(X)]. Don't forget!>
	MSG	<FALCO OTHER The [(X)] button activates your boosters!>
	MSG	<PEPPY OTHER Use [(X)] to boost your speed!>
	MSG	<SLIPPY OTHER Pressing [(X)] makes you fly faster! Rrrribbit!>
	MSG	<GIRL1 OTHER To speed up, press [(X)] to activate boosters!>
	MSG	<GIRL2 OTHER You can boost your speed by using [(X)]!>
	MSG	<FOX OTHER Chase the enemy down with [(X)]!>
	MSG	<FALCO OTHER You're flying too slow! Use [(X)] to boost  speed.>
	MSG	<PEPPY OTHER The enemy is way ahead of us. Use [(X)] to speed up!>
	MSG	<SLIPPY OTHER They're getting away! Boost speed with [(X)]-crrroak!>
	MSG	<GIRL1 OTHER We're far behind! Catch up by using [(X)]!>
	MSG	<GIRL2 OTHER You'll have to use [(X)] to chase the enemy down.>
	MSG	<ANDROSS OTHER Ah! So your resolve is strong! Now it's time to get serious.>
	MSG	<PEPPER HELP A Planet Cannon's charging. You must attack the carrier!>
	MSG	<PEPPER OTHER The enemy's charging the Planet Cannon! Destroy them quickly!>
	MSG	<ANDROSS OTHER Not bad...not bad at all, Star Fox.>
	MSG	<ANDROSS OTHER You are improving, Star Fox.>
	MSG	<ANDROSS OTHER So, you made it this far. I've been waiting for you.>
	MSG	<ANDROSS HELP Impressive!-but your existence ends here.>
	MSG	<ANDROSS HELP You are just a puppet of that fool Pepper!>
	MSG	<ANDROSS HELP You've interfered for the last time, Cornerian dogs!>
	MSG	<ANDROSS DOWN I will put you to rest. Don't worry- it will be quick.>
	MSG	<ANDROSS DOWN I have not yet forgotten what you did to me before.>
	MSG	<ANDROSS DOWN Everything is in my control! In the end, you'll weep.>
	MSG	<FOX OTHER There is a missile heading toward Corneria! Stop it!>
	MSG	<FALCO OTHER Ah ha! A missile has been launched! Let's destroy it!>
	MSG	<PEPPY OTHER A missile's been sighted heading for Corneria!>
	MSG	<SLIPPY OTHER Ribbit! There's a missile headed for Corneria!>
	MSG	<GIRL1 OTHER Yow! Corneria's been targeted by a missile!>
	MSG	<GIRL2 OTHER Emergency! Missile headed for Corneria!>
	MSG	<FOX OTHER That should stop  missiles coming from that planet!>
	MSG	<FALCO OTHER Ha! Andross's bases are nothing!>
	MSG	<PEPPY OTHER All right! No more missiles from that planet!>
	MSG	<SLIPPY OTHER We did it! The base and its missiles are gone!>
	MSG	<GIRL1 OTHER Ha, ha, ha! That base wasn't too tough!>
	MSG	<GIRL2 OTHER No base means no more missiles from that planet!>
	MSG	<FOX OTHER Okay! We took it out! Now our job is easier.>
	MSG	<FALCO OTHER It was big, but it wasn't too tough for us!>
	MSG	<PEPPY OTHER That was a major blow to the enemy!>
	MSG	<SLIPPY OTHER The Battle Carrier was not so bad. Let's move on!>
	MSG	<GIRL1 OTHER Destroying the carrier destroys the fighters, too!>
	MSG	<GIRL2 OTHER Our job is easier once we destroy the carriers.>
	MSG	<WOLF DOWN I'm impressed, Star Fox. You are talented...>
	MSG	<CHAMELEON DOWN Yikes! Cap'n Wolf is gonna have to deal with you!>
	MSG	<PIG DOWN Unbelievable! I must be getting old or something!>
	MSG	<MONKEY DOWN Aaaargh! We won't forget this! Nooo!>
	MSG	<WOLF DOWN Today, I lose. But tomorrow I shall crush you!>
	MSG	<CHAMELEON OTHER Ha! Leon of the Star Wolf wing is now here!>
	MSG	<PIG OTHER I'm Pigma of the Star Wolf wing! Behold my talent!>
	MSG	<MONKEY OTHER My name is Algy, and I own you. Come on!>
	MSG	<WOLF OTHER Pepper deceived you. I am the best pilot in Lylat.>
	MSG	<CHAMELEON OTHER Cap'n Wolf has ordered me to crush you.>
	MSG	<PIG OTHER Andross paid me well. This will be an easy job!>
	MSG	<MONKEY OTHER Cap'n Wolf told me the Star Fox team was nothing!>
	MSG	<WOLF OTHER Worthless cowards. You act tough, but I'll destroy you.>
	MSG	<PEPPER OTHER The enemy's taken the satellite platform. Help us!>
	MSG	<WOLF OTHER My opponents always evaporate into space dust!>
	MSG	<CHAMELEON OTHER Ho, ho! You have some skills, but I will not lose!>
	MSG	<PIG OTHER You're not bad-  for an amateur!>
	MSG	<MONKEY OTHER There is no safe place for you now!>
	MSG	<WOLF OTHER Hear me, Star Fox! I, Star Wolf, will defeat you now!>
	MSG	<FOX OTHER Way to go! You did it, but I was a bit worried.>
	MSG	<FALCO OTHER I got worried, and I wanted to take your place.>
	MSG	<PEPPY OTHER Are you okay? Now that was a test of your skills!>
	MSG	<SLIPPY OTHER Crrroak! I thought it was all over for a minute!>
	MSG	<GIRL1 OTHER Good job! That was a nail-biter!>
	MSG	<GIRL2 OTHER Whew! We almost didn't get out of that scrape!>
	MSG	<FOX SPECIAL It's all right! You just gotta believe!>
	MSG	<FALCO SPECIAL You shouldn't have worried, it wasn't that tough!>
	MSG	<PEPPY SPECIAL Hey, it was no problem! Piece of cake!>
	MSG	<SLIPPY SPECIAL Rrribbit! That's right! I was nervous, too.>
	MSG	<GIRL1 SPECIAL Pardon? It was easy! Remember, I've got skills!>
	MSG	<GIRL2 SPECIAL What? It wasn't all that bad...we toasted 'em!>
	MSG	<PEPPER OTHER Your Mothership. Use the ship to power up shields and warp.>
	MSG	<PEPPER DOWN The satellite is attacking Corneria. Recapture it!>
	MSG	<PEPPER OTHER The defense system destroyed an enemy target.>
	MSG	<FOX OTHER Quickly press [(L)] or [(R)] twice to avoid enemy shots.>
	MSG	<FALCO OTHER Press [(L)] or [(R)] twice, and you can avoid shots.>
	MSG	<PEPPY OTHER Quickly tap [(L)] or [(R)] twice to avoid enemy shots.>
	MSG	<SLIPPY OTHER To roll and avoid enemy shots, tap [(L)] or [(R)] twice.>
	MSG	<GIRL1 OTHER Tap [(L)] or [(R)] twice to roll and dodge enemy shots.>
	MSG	<GIRL2 OTHER To avoid enemy shots, quickly tap [(L)] or [(R)] twice.>
	MSG	<PEPPER OTHER Let me tell you how to control a Walking craft.>
	MSG	<PEPPER OTHER Use [DPAD] to control the direction, and [(L)] and [(R)] to spin.>
	MSG	<PEPPER OTHER To move faster, tap [DPAD] twice in any direction.>
	MSG	<PEPPER OTHER Use [(Y)] to jump. Press [SLCT] to transform.>
	MSG	<PEPPER OTHER Make good use of the transforming  capabilities.>
	MSG	<PEPPER HELP The satellite has been overrun. Take it back!>
	MSG	<PEPPER OTHER Finally, Andross's forces in the Lylat system are defeated!>
	MSG	<PEPPER OTHER Press on! You must neutralize Andross once and for all!>
	MSG	<PEPPER OTHER Switch positions with your wing man by pressing [SLCT].>
	MSG	<PEPPER OTHER Use [(B)] to jump, and press [SLCT] to transform.>
	MSG	<PEPPER OTHER Blaster level now raised. Homing shots enabled!>
	MSG	<PEPPER OTHER Place the target marker on an enemy and fire!>
	MSG	<PEPPER OTHER You've located a secret base! Try to gain entrance.>
