;****************************************************
;	port2 level sound label for fox2  95. 6.26
;	(dist-size check version) 
;****************************************************

;========= port 2 ========
	km_port2labelstart

	km_port2label	port2_stop	;00

	km_port2smlabel	p2_wolf_arwing	;01
	km_port2smlabel	p2_speed_s	;01
	km_port2smlabel	p2_help_robot	;01
	km_port2smlabel	p2_demo_arwing	;01
	km_port2label	p2_airplane	;01

	km_port2label	p2_EMissile	;02

;	km_port2smlabel	p2_d_sen_ss	;03
;	km_port2smlabel	p2_enemy_base	;03
;	km_port2label	p2_boss_coming	;03

	km_port2label	p2_ERing	;03

	km_port2smlabel	p2_zako_2	;04
	km_port2smlabel	p2_hae_0	;04
	km_port2label	p2_enemy_fly1	;04

	km_port2smlabel	p2_androf_eye	;05	;0E
	km_port2smlabel	p2_ironball	;05
	km_port2smlabel	p2_kaku6_4	;05
	km_port2smlabel	p2_ninja	;05
	km_port2smlabel	p2_poyon	;05
	km_port2smlabel	p2_kaoman	;05
	km_port2smlabel	p2_enban_1	;05
	km_port2label	p2_sos_2	;05
;	km_port2label	p2_space_ship	;05

	km_port2smlabel	p2_dragon	;06
	km_port2smlabel	p2_kururin	;06
	km_port2smlabel	p2_baku		;06
	km_port2smlabel	p2_jyouge_1	;06
	km_port2smlabel	p2_crusher	;06
	km_port2smlabel	p2_chika_k3	;06
	km_port2smlabel	p2_iwashi_0l	;06
	km_port2smlabel	p2_sagyou_0	;06
	km_port2smlabel	p2_sos_1	;06
	km_port2smlabel	p2_ship_0	;06
	km_port2smlabel	p2_zako1	;06
	km_port2smlabel	p2_kani_0	;06
	km_port2smlabel	p2_f_robo_0	;06
	km_port2label	p2_rapyuta	;06

	km_port2smlabel	p2_inseki	;07
	km_port2smlabel	p2_you_0_0	;07
	km_port2label	p2_room		;07

	km_port2smlabel	p2_cup_0	;08
	km_port2smlabel	p2_tate_m_0	;08
	km_port2smlabel	p2_yoi_hou	;08
	km_port2smlabel	p2_b_tank_2	;08
	km_port2smlabel	p2_r_an_0	;08
	km_port2smlabel	p2_guru2bar	;08
	km_port2smlabel	p2_c_cup_1	;08
	km_port2label	p2_antenna	;08

	km_port2smlabel	p2_core_motor	;09
	km_port2smlabel	p2_runner_3	;09
	km_port2smlabel	p2_shizumu	;09
	km_port2smlabel	p2_f_fune	;09
	km_port2smlabel	p2_grd_dandou	;09
	km_port2label	p2_track_0	;09

	km_port2smlabel	p2_jyouge	;0A
	km_port2smlabel	p2_enkin	;0A
	km_port2smlabel	p2_ka_0		;0A
	km_port2label	p2_enemy_fly2	;0A

	km_port2smlabel	p2_taigun	;0B
	km_port2smlabel	p2_sos_0	;0B
	km_port2smlabel	p2_zako_0	;0B
	km_port2label	p2_enemy_fly3	;0B

	km_port2smlabel	p2_ESmasher	;0C
	km_port2label	p2_EPlasma	;0C

	km_port2smlabel	p2_androf_fire	;0D	;0F	;sdst1
	km_port2smlabel	p2_da_ha_ta	;0D
	km_port2label	p2_fire_breath	;0D

;tensou
	km_port2smlabel	p2_demo_arwing2	;0E	;mes_talk	
	km_port2smlabel	p2_d_sen_ss	;06	;sdst2
	km_port2smlabel	p2_yoyo_c	;0E	;sdst3,sdst7
;	km_port2smlabel	p2_space_ship	;0E	;sdst2
	km_port2smlabel	p2_virus	;0E	;sdst4
	km_port2smlabel	p2_r_tank_0	;0E	;sdst3,sdst7
	km_port2smlabel	p2_miss2_1	;0E	;sdst5
	km_port2smlabel	p2_dandou	;0E	;sdst5
	km_port2label	p2_pierrot_beamball	;0E

	km_port2smlabel	p2_andorf_magic2	;0F	;sdst2
	km_port2smlabel	p2_wolf_laser	;0F	;sdst5
	km_port2smlabel	p2_system_3	;0F	;sdst4
	km_port2smlabel	p2_stepup_0	;0F	;sdst1
	km_port2smlabel	p2_egu_0	;0F	;sdst3
	km_port2label	p2_d_sen_ss_laser	;0F	;sdst5


;	km_port2labelstart
;	km_port2label	port2_stop	;00
;	km_port2label	p2_airplane	;01
;	km_port2label	p2_missile	;02
;	km_port2label	p2_boss_coming	;03
;	km_port2label	p2_enemy_fly1	;04
;	km_port2label	p2_space_ship	;05
;	km_port2label	p2_laputa	;06
;	km_port2label	p2_room		;07
;	km_port2label	p2_antenna	;08
;	km_port2label	se9		;09
;	km_port2label	p2_boss_beamball	;0A
;	km_port2label	p2_enemy_fly2	;0B
;	km_port2label	p2_enemy_fly3	;0C
;	km_port2label	p2_beamball	;0D
;	km_port2label	p2_ring		;0E
;	km_port2label	p2_fire_breath	;0F
;
;****************************************************
;	port3 trigger label for fox2	H7. 7. 3
;****************************************************

;========= port 3 ========

	km_port3labelstart
;$00
	km_port3label	nosound		;$00
	km_port3label	pauseoff	;$01
	km_port3label	pauseon		;$02
	km_port3label	cursor		;$03
	km_port3smlabel	right_chime	;$04*
	km_port3smlabel	map_battle_start	;$04*
	km_port3label	kettei		;$04
;	km_port3smlabel	marubatsu	;$05*
	km_port3label	next_message	;$05
;	km_port3label	wing_move_end	;$05
	km_port3smlabel	e_message_open	;$06
	km_port3label	openwindow	;$06
	km_port3smlabel	e_message_close	;$07
	km_port3label	closewindow	;$07
	km_port3label	cancel		;$08
;	km_port3label	nice		;$09
	km_port3label	line_message	;$09
;	km_port3label	addscore	;$0a
	km_port3label	mother_ship_warp	;$0a
	km_port3smlabel	ship_cursor_set	;$0b*
	km_port3smlabel	map_enemy_check	;$0b
	km_port3label	star_select	;$0b
	km_port3smlabel	marubatsu	;$0c*
	km_port3label	map_place_set	;$0c
	km_port3label	ringoutcount	;$0d
	km_port3label	demo_cancel	;$0e
	km_port3smlabel	tunnel_explode	;$0f
	km_port3label	corneria_explode	;$0f
;$10
	km_port3label	shipdown	;$10
	km_port3label	myshield0	;$11
	km_port3smlabel	pl_explode_s	;$12*
	km_port3label	damage_l	;$12
	km_port3label	damage_s	;$13
	km_port3label	shield_item	;$14
	km_port3label	Roboshield0	;$15
	km_port3smlabel	line_over_1	;$16*
	km_port3label	salarm_s	;$16
	km_port3smlabel	line_over_2	;$17*
	km_port3label	salarm_h	;$17
	km_port3smlabel	name_set_cursol	;$18*
	km_port3label	shieldreflect	;$18
	km_port3label	RobolandInSea_l	;$19
;	km_port3label	barrierreflect	;$19
	km_port3smlabel	map_run_away	;$1a*
	km_port3label	boost		;$1a
	km_port3label	brake		;$1b
	km_port3label	transArwing2Robo	;$1c
	km_port3label	transRobo2Arwing	;$1d
	km_port3label	transArwing2RoboEnd	;$1e
	km_port3label	transRobo2ArwingEnd	;$1f
;$20
;	km_port3label	RobolandInSea_l	;$20
;	km_port3label	pl_explode_s	;$21

	km_port3label	longlaser1	;$20
	km_port3smlabel	longlaser2	;$21
	km_port3label	secret_metal	;$21
	km_port3label	Robowalkinsea1	;$22
	km_port3smlabel	Robowalkinsea2	;$23*
	km_port3smlabel	reboundlaser2	;$23*
	km_port3label	barrier_hit	;$23
	km_port3label	Robowalk1	;$24
;	km_port3smlabel	Robowalk2	;$25*
;	km_port3label	cornelia_sos	;$25
	km_port3label	pepper_voice	;$25
	km_port3label	arwinglaser1	;$26
	km_port3smlabel	arwinglaser2	;$27
	km_port3label	twinblaster	;$27
	km_port3label	arwingbmball1	;$28
	km_port3smlabel	arwingbmball2	;$29*
	km_port3label	s_metal_appear	;$29
	km_port3label	bomshoot	;$2a
	km_port3smlabel	map_laser_explode	;$64
	km_port3smlabel	bs_core_death	;$2b*
	km_port3smlabel	mis_explode	;$2b*
	km_port3label	bomexplode	;$2b
	km_port3label	Roboland_l	;$2c
	km_port3label	Roboland_s	;$2d
	km_port3label	Robojmp		;$2e
	km_port3label	viewchange	;$2f

;$30
	km_port3smlabel	CatchMedal	;$30*
	km_port3smlabel	you_are_right	;$30*
	km_port3label	GateRing	;$30
	km_port3smlabel	recoverHP	;$31*
	km_port3label	shot_charge_start	;$31
	km_port3label	CatchHeart	;$32
	km_port3smlabel	pool_swimming	;$33*

	km_port3label	WaterWalk	;$33
	km_port3label	you_are_wrong	;$34*
	km_port3smlabel	overheat_warning ;$35*
	km_port3label	shot_charge	;$35
;	km_port3label	s_charging	;$36
	km_port3smlabel	altitude_limit	;$36*
	km_port3label	trans_unable	;$36
;	km_port3label	ringoutless5	;$37

	km_port3label	heal_parts	;$37
	km_port3label	shieldrecover	;$38
	km_port3label	StopArmRoll	;$39
;	km_port3label	steponpanel	;$3a
;	km_port3label	seabeamball	;$3b

	km_port3label	twinbmball1	;$3a
	km_port3smlabel	twinbmball2	;$3b*
;	km_port3label	wolfteam_appear	;$3b
	km_port3label	lock_on		;$3b
	km_port3smlabel	system_charge	;$3c*
	km_port3label	wingwaterdmg	;$3c
	km_port3label	roboswim	;$3d
	km_port3label	inmarine	;$3e
	km_port3label	outmarine	;$3f

;$40
	km_port3smlabel	help		;$40
	km_port3label	tsushin_start	;$40
	km_port3smlabel	thanks		;$41*
	km_port3label	door_open_chime	;$41
	km_port3smlabel	boss_come	;$42*
	km_port3smlabel	end_push_start	;$42*
	km_port3label	exp_good_luck	;$42
	km_port3label	twin_blaster	;$43
	km_port3label	en_cry_3	;$44
	km_port3label	special_weapon	;$45
;	km_port3smlabel	robot_bound	;$46*
	km_port3label	partner_boost	;$46
	km_port3label	tsushin_end	;$47
	km_port3label	good_luck	;$48
	km_port3label	p_warning_0	;$49
	km_port3label	p_warning_1	;$4a
	km_port3label	p_warning_2	;$4b
;	km_port3label	message		;$4c
	km_port3label	wolf_voice	;$4c
	km_port3label	andrew_voice	;$4d
	km_port3label	leon_voice	;$4e
	km_port3label	pigma_voice	;$4f

;$50
	km_port3label	ryoukai_fox	;$50
	km_port3label	ryoukai_falco	;$51
	km_port3label	ryoukai_peppy	;$52
	km_port3label	ryoukai_slippy	;$53
	km_port3label	ryoukai_gal_1	;$54
	km_port3label	ryoukai_gal_2	;$55
;
;	km_port3smlabel	fox_voice	;$4a
;	km_port3smlabel	falco_voice	;$4b
;	km_port3smlabel	peppy_voice	;$4c
;	km_port3smlabel	slippy_voice	;$4d
;	km_port3smlabel	gal_1_voice	;$4e
;	km_port3smlabel	gal_2_voice	;$4f
;
	km_port3label	player_message	;$56
	km_port3label	player_warning	;$57
	km_port3label	partner_message	;$58
	km_port3label	partner_warning	;$59
	km_port3smlabel	gameover_voice	;$5a	;$4e
	km_port3label	talking01	;$5a
	km_port3smlabel	white_wipe	;$5b*
	km_port3smlabel	continue_voice	;$5b*	;$4f
	km_port3smlabel	androf_voice	;$5b*
	km_port3label	talking02	;$5b

;	km_port3label	partner_laser	;$5c
	km_port3smlabel	total_score	;$5c
	km_port3label	add_time	;$5c

	km_port3label	androf_voice_0	;$5d
	km_port3label	androf_voice_1	;$5e
	km_port3label	androf_voice_2	;$5f

;$60
	km_port3label	en_map_encount2	;$60
	km_port3smlabel	bs_cube_open	;$61	;$c2
	km_port3smlabel	bs_cube_close	;$61*
	km_port3smlabel	en_taiman_appear	;$61*
	km_port3smlabel	en_wolf_appear	;$61*
	km_port3label	en_sos_appear	;$61

	km_port3smlabel	en_mis_hassha	;$62*
	km_port3label	en_sos_hassha	;$62

	km_port3smlabel	en_b_ship_appear	;$63*
	km_port3label	en_star_senryou	;$63

	km_port3label	system_shot	;$64
	km_port3smlabel	en_dmg_2	;$65*
	km_port3label	en_core_dmg_big	;$65
	km_port3label	disp_noise	;$66
	km_port3label	disp_sand_storm	;$67
	km_port3label	count_up_gauge	;$68
;	km_port3label	en_tekikan_demo	;$68
;	km_port3smlabel	en_kamakiri	;$69*
	km_port3label	en_tekuteku	;$69
	km_port3smlabel	en_kamakiri_kids	;$6a*
	km_port3smlabel	en_hasami	;$6a	;$7c
	km_port3label	en_tekuteku_s	;$6a
;	km_port3smlabel	en_suisui	;$6b*
	km_port3label	en_laser_charge	;$6b
	km_port3label	en_amenbo_walk	;$6c
;	km_port3smlabel	en_step_appear	;$6d*
	km_port3label	overheat	;$6d
	km_port3label	en_map_encount	;$6e
	km_port3label	map_open_wipe	;$6f

;$70
	km_port3label	en_explode_s	;$70
	km_port3label	en_dmg_s	;$71
	km_port3label	en_laser_sL	;$72
	km_port3label	en_ringlaser_s	;$73
	km_port3smlabel	en_tank_shoot	;$74
	km_port3label	en_missileshoot_s	;$74

	km_port3label	en_ERing_shot	;$75

	km_port3label	en_land_L	;$76
	km_port3smlabel	en_mizukara_jump	;$77*
	km_port3smlabel	ob_arm_punch	;$77*
	km_port3smlabel	ob_toge_slide	;$77*
	km_port3label	en_jump1_L	;$77
	km_port3smlabel	en_spiderwork_L	;$78*	;$80
	km_port3label	en_yamori_walk	;$78
	km_port3smlabel	en_death_2	;$79
	km_port3label	en_cry1_s	;$79
	km_port3label	en_Land_2	;$7a
	km_port3label	en_ERing_charge	;$7b
	km_port3label	en_death_3	;$7c
	km_port3smlabel	en_kurage_getup	;$7d*
	km_port3smlabel	en_kururin	;$7d*
	km_port3label	en_floweropen	;$7d
	km_port3label	en_dash_demo	;$7e
	km_port3label	en_wormappear	;$7f
;$80
	km_port3label	en_cry_2	;$80	;$40

	km_port3label	en_bird_cry	;$81

	km_port3smlabel	bs_dragon_through	;$82*
	km_port3label	en_feather_L	;$82
	km_port3label	en_plasma	;$83
	km_port3smlabel	en_to_hou	;$84*
	km_port3smlabel	en_tail_swing	;$84*
	km_port3label	en_arm_swing	;$84
	km_port3smlabel	en_throw_2	;$85*
	km_port3smlabel	bs_throw	;$85*
	km_port3label	en_throw	;$85
	km_port3label	en_meteor_kani	;$86
	km_port3smlabel	en_teku_jump	;$87*
	km_port3label	en_jump2	;$87
	km_port3smlabel	pillar_of_flames	;$88
	km_port3smlabel	en_yoyo_c_open	;$88*
	km_port3label	en_inmarine	;$88
	km_port3smlabel	en_yoyo_c_close	;$89*
	km_port3label	en_outmarine	;$89

	km_port3label	en_kaoman_down	;$8a

	km_port3label	en_explode_demo	;$8b
	km_port3label	en_bird_bound	;$8c
	km_port3label	en_wingroll	;$8d
	km_port3smlabel	crusher_shield	;$8e*
	km_port3smlabel	face_broken2	;$8e*
	km_port3label	en_missile_bunri	;$8e
	km_port3label	en_kieru	;$8f

;$90

	km_port3smlabel	ob_ana_0_up	;$90*
	km_port3smlabel	ob_movewall_SL	;$90*
	km_port3label	ob_totem_up	;$90
	km_port3smlabel	ob_ana_0_down	;$91*
	km_port3label	ob_movewall_down	;$91
	km_port3label	ob_opendoor_s	;$92
	km_port3label	ob_closedoor_s	;$93
	km_port3label	ob_bubble1	;$94
	km_port3smlabel	ob_core_up_down	;$95*
	km_port3label	ob_item_box_up	;$95
	km_port3label	ob_damege_spark	;$96
	km_port3smlabel	ob_tousen_roll	;$97*
	km_port3smlabel	ob_base_up	;$97*
	km_port3label	ob_mothership_hatch	;$97
	km_port3label	ob_bun		;$98
	km_port3smlabel	ob_t_to_1_open	;$99*	;$a0
	km_port3label	ob_bunhard_L	;$99
	km_port3label	ob_bunsoft_L	;$9a
	km_port3smlabel	bs_disappear	;$9b*
	km_port3label	ob_black_barrior	;$9b
	km_port3label	ob_base_door	;$9c
	km_port3label	ob_tousen_move	;$9d
;
;	km_port3label	ob_openhacci	;$9c
;	km_port3label	ob_closehacci	;$9d
;
	km_port3label	ob_reboundlaser_s	;$9e
	km_port3smlabel	en_ninja_wing	;$9f*
	km_port3label	ob_ha_hou_door	;$9f

;$a0
	km_port3label	ob_bunhard_end	;$a0
	km_port3label	ob_bunsoft_end	;$a1

	km_port3smlabel	en_egu_0_open	;$a2*
	km_port3smlabel	ob_room_hou_out	;$a2*
	km_port3label	ob_room_hou_in	;$a2

	km_port3label	ob_moai_move	;$a3
	km_port3label	ob_switchon	;$a4
	km_port3label	ob_yuka_hou_out	;$a5
	km_port3label	ob_yuka_hou_in	;$a6
	km_port3label	wallreflect	;$a7
	km_port3label	ob_push_door	;$a8
	km_port3label	ob_up_to_the_sky	;$a9
;	km_port3smlabel	ob_bound_on_magma	;$aa*
	km_port3label	ob_demo_door	;$aa
	km_port3label	ob_throughObst_L	;$ab
	km_port3label	en_egu_0_close	;$ac
	km_port3label	ob_slide_switch	;$ad
	km_port3label	ob_roll_switch	;$ae

	km_port3label	d_sen_ss_laser	;$af

;$b0
	km_port3label	ob_core_explode	;$b0
	km_port3smlabel	BIg_Explode	;$b1*
	km_port3label	bs_BossExplode	;$b1
	km_port3label	bs_core_fall	;$b2
	km_port3label	bs_cry_1	;$b3
	km_port3label	bs_cry_2	;$b4
	km_port3label	face_broken1	;$b5
	km_port3label	bs_monster_down	;$b6
;	km_port3label	bs_pierrot_breath	;$b7
	km_port3label	bs_dragon_laser2	;$b7
;	km_port3label	bs_hand_move	;$b8		;not use
	km_port3label	ob_core_thud	;$b8
	km_port3smlabel	bs_throw_last	;$b9		;not use
	km_port3label	en_wolf_s_shot	;$b9
	km_port3smlabel	bs_pierrot_voice	;$ba*
	km_port3label	bs_core_cover_down	;$ba
	km_port3smlabel	bs_pierrot_damage	;$bb
	km_port3label	andorf_down	;$bb
	km_port3label	bs_dragon_cry	;$bc
	km_port3label	bs_dragon_laser	;$bd
	km_port3label	en_dragon_kamu	;$be
	km_port3label	bs_andorf_damage	;$bf

;$c0
	km_port3smlabel	record_clear	;$c0*	;$70
	km_port3smlabel	bs_BossExplode2	;$c0
	km_port3smlabel	map_base_explode	;$c0
	km_port3label	bs_base_explode	;$c0
	km_port3label	bs_androf_magic	;$c1
	km_port3label	wolf_flash	;$c2
	km_port3label	bs_magic_stop	;$c3
	km_port3label	map_laser	;$c4
	km_port3label	map_laser_charge1	;$c5
	km_port3label	map_laser_charge2	;$c6
	km_port3label	map_laser_charge3	;$c7
	km_port3label	face_close	;$c8
	km_port3label	bs_kamakiri	;$c9
	km_port3smlabel	en_arm_set	;$ca*
	km_port3label	hatch_move_end	;$ca
	km_port3smlabel	leveltrig_stop	;$cb*
	km_port3label	stop_tr7	;$cb
	km_port3label	stop_tr3	;$cc
;	km_port3label	stop_tr45	;$cd
	km_port3label	stop_tr2	;$cd
	km_port3label	stop_tr4	;$ce
	km_port3label	stop_tr5	;$cf

;$d0
	km_port3label	nosoundd0	;$d0
	km_port3label	nosoundd1	;$d1
	km_port3label	nosoundd2	;$d2
	km_port3label	nosoundd3	;$d3
	km_port3label	nosoundd4	;$d4
	km_port3label	nosoundd5	;$d5
	km_port3label	nosoundd6	;$d6
	km_port3label	nosoundd7	;$d7
	km_port3label	nosoundd8	;$d8
	km_port3label	nosoundd9	;$d9
	km_port3label	nosoundda	;$da
	km_port3label	nosounddb	;$db
	km_port3label	nosounddc	;$dc
	km_port3label	nosounddd	;$dd
	km_port3label	nosoundde	;$de
	km_port3label	nosounddf	;$df

;$e0
	km_port3label	nosounde0	;$e0
	km_port3label	nosounde1	;$e1
	km_port3label	nosounde2	;$e2
	km_port3label	nosounde3	;$e3
	km_port3label	nosounde4	;$e4
	km_port3label	nosounde5	;$e5
	km_port3label	nosounde6	;$e6
	km_port3label	nosounde7	;$e7
	km_port3label	nosounde8	;$e8
	km_port3label	nosounde9	;$e9
	km_port3label	nosoundea	;$ea
	km_port3label	nosoundeb	;$eb
	km_port3label	nosoundec	;$ec
	km_port3label	nosounded	;$ed
	km_port3label	nosoundee	;$ee
	km_port3label	nosoundef	;$ef

;$f0
	km_port3label	trig_se_unable	;$f0
	km_port3label	trig_unable	;$f1
	km_port3label	trig_mute_off	;$f2
	km_port3label	trig_mute_on	;$f3
	km_port3smlabel	upgauge_init  	;$f4
	km_port3label	charge_stop	;$f4
;	km_port3label	sos_demo_on	;$f4
	km_port3label	stereo		;$f5
	km_port3label	monoral		;$f6
	km_port3label	demo_off	;$f7
	km_port3label	demo_on		;$f8
	km_port3label	place_space	;$f9
	km_port3label	place_room	;$fa
	km_port3label	place_ground	;$fb
	km_port3label	place_sea	;$fc
	km_port3label	battle_mode	;$fd
	km_port3label	mission_mode	;$fe
	km_port3label	stop		;$ff

;	1995. 4.18
;	km_port3smlabel	ob_koma_roll	;$ac
;	1995. 1.25
;	km_port3label	en_houdai_s	;$75
;	km_port3label	en_monkeywork_L	;$81
;	km_port3label	en_hana_hou	;$8a
;	km_port3label	ob_soft_jump	;$a2
;	km_port3label	ob_crystal_bound	;$af


;	km_port3label	en_monkeyLjump	;$83
;	km_port3label	en_monkeySjump	;$84
;	km_port3label	ob_sarubomb_s	;$97

;	km_port3label	shield_1	;$34
;	km_port3label	steponpanel_end	;$3b
;	km_port3label	en_bara_s	;$7b
;	km_port3label	ob_bubble2	;$95
;	km_port3label	ob_kinokonobi	;$9b
;	km_port3label	ob_panel_ball	;$9f
;	km_port3label	ob_stopwall_up	;$a5
;	km_port3label	ob_stopwall_down	;$a6
;	km_port3label	ob_wall_stop	;$a7
;	km_port3label	ob_body_bound	;$a8
;







