#######################
# Star Fox 2 Makefile #
#######################

STDFILES= INC\HEADER.INC INC\MACROS.INC VARS.INC INC\SOUNDEQU.INC INC\STRUCTS.INC INC\ALCS.INC \
 INC\GILESALX.INC INC\GILESALC.INC INC\GILESAL.INC INC\KALCS.INC INC\DALCS.INC INC\PALETTES.INC \
 INC\TALCS.INC INC\YALCS.INC INC\PLAYER.INC INC\KMACS.INC INC\TMACROS.INC INC\KVARS.INC INC\MVARS.INC \
 INC\SOUND.INC INC\SOUND2.INC INC\MYVARS.INC INC\MTVARS.INC INC\MKVARS.INC
STRATFILES= INC\STRATMAC.INC INC\STRATLIB.INC INC\STRATEQU.INC INC\SHMACS.INC INC\STRATHDR.INC \
 INC\WEAPONS.INC INC\SCALEVAR.INC
ASM=ARGSFXX
ASMFLAGS=-efilelist=0 -xsymbols.txt
include symson.mak
LINK=arglink
LOPTS=-b30 -h1024
ANSI=

ALLFILES= BANK\bank0.sob BANK\bank1.sob BANK\bank2.sob \
 BANK\bank4.sob BANK\bank5.sob BANK\bank6.sob BANK\bank7.sob \
 BANK\bank8.sob BANK\bank10.sob BANK\bank11.sob BANK\shbanks.sob BANK\incbins.sob BANK\incbins2.sob

.asm.sob:
	@$(ASM) -m30 $(ANSI) $(SYMSON) $(ASMFLAGS) $< -v$*.SOB

all: finished.sg

     
finished.sg: $(ALLFILES)
	@$(LINK) $(LOPTS) -d @flist

sf.rom: $(ALLFILES)
	@$(LINK) $(LOPTS) -osf.rom @flist

info: $(ALLFILES)
	@$(LINK) $(LOPTS) -l1024 @flist

remote: $(ALLFILES)
	@$(LINK) $(LOPTS) -oromfile @flist
	@+ftprom.btm
	

## Bank 0
bank0.sob: BANK\bank0.asm $(STRATFILES) \
$(STDFILES) ASM\blink.asm data\etabs.dat ASM\sgtabs.asm \
data\nintendo.pal FONT\font_1.bin MSG\japanese.msg \
MSG\english.msg ASM\sgdata.asm ASM\istrats.asm \
SHAPES\ushapes.asm SHAPES\pshapes.asm SHAPES\pshapes2.asm SHAPES\pshapes3.asm SHAPES\shapes.asm \
SHAPES\shapes2.asm SHAPES\bshapes.asm SHAPES\wshapes.asm SHAPES\eshapes.asm \
SHAPES\eshapes2.asm FONT\mmj.bin FONT\mme.bin ASM\techdata.asm

## Bank 1
## MSLOPES HAS TO BE IN THE ROOT OF THE SF2 DIRECTORY
bank1.sob: BANK\bank1.asm INC\shmacs.inc INC\gamemsgs.inc \
$(STDFILES) MARIO\mmacs.mc MARIO\mshtab.mc MARIO\mmaths.mc MARIO\mwrot.mc \
MARIO\mwcrot.mc MARIO\mobj.mc MARIO\mclip.mc MARIO\mtxtclp.mc \
MARIO\mdrawp.mc MARIO\msprite.mc MARIO\mgdots.mc MARIO\mcircle.mc \
MARIO\mscreen.mc MARIO\mcursor.mc MARIO\mdrawlis.mc MARIO\mdecru.mc \
MARIO\mtxtprt.mc MARIO\mplanet.mc MARIO\mdsprite.mc MARIO\mpart.mc \
MARIO\mbumwipe.mc MARIO\mhud.mc MARIO\mhofs.mc MARIO\mdebug.mc \
MARIO\mplanclp.mc MARIO\mboxes.mc \
data\moji_d.fon data\moji_d.trn ASM\gametext.asm ASM\fontdata.asm \
ASM\defspr.asm data\p_col.col ASM\coltab.asm \
ASM\light.asm ASM\coltabs.asm mslopes.mc


## Bank 2, 3
bank2.sob: BANK\bank2.asm INC\bgmacs.inc $(STRATFILES) INC\olsmacs.inc INC\mapmacs.inc INC\mapstruc.inc INC\sound.inc INC\sound2.inc INC\gamelist.inc\
$(STDFILES) ASM\irq.asm ASM\showview.asm ASM\hdmatabs.asm \
ASM\mem.asm ASM\ramsrou.asm ASM\colboxes.asm ASM\coldet.asm \
ASM\ramspr.asm ASM\mmtbl.asm ASM\soslist.asm ASM\kramcalc.asm ramsound.asm \
INC\yajima.inc ASM\yjradar.asm ASM\raster.asm ASM\rammes.asm \
ASM\ramstuff.asm ASM\trans.asm ASM\main.asm ASM\game.asm \
ASM\obj.asm ASM\planets.asm ASM\world.asm ASM\sysstrat.asm \
ASM\stratrou.asm ASM\nmi.asm ASM\screen.asm ASM\intro.asm \
ASM\bgs.asm ASM\windows.asm ASM\sndtbl.asm ASM\sound.asm ASM\draw.asm \
ASM\mapscr.asm ASM\debug.asm ASM\bootnmi.asm ASM\kcalc.asm \
ASM\titlesub.asm

## Bank 4
bank4.sob: BANK\bank4.asm INC\bgmacs.inc INC\gamelist.inc\
$(STDFILES) ASM\sprites.asm ASM\sprsub.asm ASM\kscrdata.asm \
ASM\kscreen.asm  ASM\hvscroll.asm \
ASM\mismap.asm ASM\mismapsub.asm ASM\rammismap.asm ASM\mapanime.asm \
ASM\config.asm ASM\title.asm

## Bank 5, bank 13
bank5.sob: BANK\bank5.asm INC\olsmacs.inc INC\mapmacs.inc ASM\istrats.asm \
$(STDFILES) maps\MAPP.asm maps\titlemap.asm maps\mis\exp1.asm \
maps\mis\stg1.asm maps\mis\stg2.asm maps\mis\stg3.asm maps\mis\stg4.asm \
maps\mis\stg5.asm maps\mis\stg6.asm maps\mis\ext1.asm maps\mis\ext2.asm \
maps\mis\ext3.asm maps\mis\ext4.asm maps\mis\sos1.asm maps\mis\sos2.asm \
maps\mis\sos3.asm maps\mis\rdstg1.asm maps\bat\bat1.asm maps\bat\bat2.asm \
maps\bat\bat3.asm maps\mis\tra1.asm \
maps\maplist.asm \
maps\mis\demo0.asm maps\mis\demo1.asm maps\mis\demo2.asm maps\mis\demo3.asm \
maps\mis\demo4.asm maps\mis\demo5.asm maps\mis\demo6.asm maps\mis\demo7.asm \
maps\mis\demo8.asm maps\mis\demo9.asm \
maps\mis\test.asm

## Bank 6
bank6.sob: BANK\bank6.asm \
$(STDFILES) $(STRATFILES) INC\players.inc ASM\player.asm \
ASM\tstrats.asm ASM\tplayer.asm ASM\kplayer.asm ASM\gakki.asm ASM\egdata.asm 

## Bank 7
bank7.sob: BANK\bank7.asm \
$(STDFILES) $(STRATFILES) INC\players.inc ASM\views.asm \
ASM\curdat.asm ASM\display.asm ASM\voffset.asm \
ASM\xplayer.asm ASM\dstrats.asm ASM\kstrats.asm 

## Bank 8
bank8.sob: BANK\bank8.asm INC\pathmacs.inc \
$(STDFILES) $(STRATFILES) pathdata.asm dpathdat.asm \
ASM\tpathdat.asm ASM\paths.asm ASM\kpathdat.asm bpathdat.asm ASM\ppathdat.asm ASM\gpathdat.asm \
ASM\paths2.asm ASM\slopes.asm ASM\mapcode.asm ASM\weapons.asm \
ASM\chart.asm fonts.asm data\arctan.asm \
ASM\result.asm

## Bank 10
bank10.sob: BANK\bank10.asm \
$(STDFILES) $(STRATFILES) \
ASM\pathkern.asm friends.asm slopedef.asm

## Bank 11
bank11.sob: BANK\bank11.asm \
$(STDFILES) $(STRATFILES) MARIO\mmacs.mc MARIO\mytest.mc \
MARIO\mmessage.mc MARIO\mkawa.mc \
ASM\oamlist.asm ASM\oamdata.asm \
ASM\wipepaus.asm ASM\oamface.asm ASM\oamplane.asm \
ASM\wipedoor.asm ASM\wipeconf.asm ASM\wipegame.asm ASM\wipepsel.asm \
ASM\wipemap.asm ASM\wipebsel.asm ASM\wipebatt.asm ASM\wipe.asm ASM\wipebeam.asm\
ASM\missobj.asm ASM\gameover.asm ASM\continue.asm ASM\gameobj.asm \
ASM\wipetitl.asm \
ASM\yjdebug.asm ASM\hell.asm yjmap.asm ASM\pselect.asm \
ASM\clear.asm ASM\pausemap.asm \
INC\yajima.inc ASM\mapexp.asm ASM\oamset.asm ASM\pselect2.asm ASM\titleobj.asm \
ASM\bestscore.asm ASM\nameset.asm ASM\mesdata.asm



## Banks 12, 13, 14, 15, 16, 17
shbanks.sob: BANK\shbanks.asm INC\shmacs.inc INC\stratequ.inc \
$(STDFILES) $(STRATFILES) SHAPES\shapes.asm SHAPES\shapes2.asm \
SHAPES\eshapes2.asm SHAPES\eshapes.asm SHAPES\bshapes.asm SHAPES\wshapes.asm \
SHAPES\ushapes.asm SHAPES\pshapes.asm SHAPES\pshapes2.asm 


## Banks 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31
incbins.sob: BANK\incbins.asm \
$(STDFILES) msprites\spt_01.bin msprites\spt_23.bin msprites\spt_45.bin \
data\a0.pcr data\a0.ccr data\a1.pcr data\a1.ccr \
data\a2.pcr data\a2.ccr data\a3.pcr data\a3.ccr \
data\a4.pcr data\a5.pcr data\a5.ccr data\a6.pcr \
data\a6.ccr data\a7.pcr data\a7.ccr data\a8.ccr \
data\a8.pcr data\a9.ccr data\a9.pcr data\a10.ccr \
data\a10.pcr data\a11.ccr data\a11.pcr data\a12.pcr \
data\a13.ccr data\a13.pcr data\a14.ccr data\a14.pcr \
data\a15.ccr data\a15.pcr data\a16.pcr data\a17.pcr \
data\a18.pcr data\a19.pcr data\a20.pcr data\a21.pcr data\a22.pcr \
data\a23.pcr data\a24.pcr data\a25.pcr \
data\e0.ccr data\e1.ccr data\e2.ccr \
data\e3.ccr data\e4.ccr data\e5.ccr data\e6.ccr data\e7.ccr \
data\w0.ccr data\w1.cgx data\w2.cgx data\b0.ccr \
data\b1.ccr data\b7.ccr data\b8.ccr \
data\b9.ccr data\b14.ccr data\b16.ccr data\b0.pcr \
data\b1.pcr data\b2.pcr data\b3.pcr data\b4.pcr \
data\b5.pcr data\b6.pcr data\b7.pcr data\b8.pcr \
data\b10.pcr data\b11.pcr data\b12.pcr data\b13.pcr \
data\b14.pcr data\b15.pcr data\b16.pcr \
data\gfx\allcols.pac data\kawaguti.cgx \
data\moji_2.fon MARIO\mdata.mc ASM\d3_3.asm ASM\sprdata.asm

## Banks 26, 27, 28, 29, 30, 31
incbins2.sob: BANK\incbins2.asm \
$(STDFILES) sound\fox2snd.bin sound\sdse1.bin sound\sdse2.bin \
sound\ffset1.bin sound\ffset2.bin \
sound\spset1.bin sound\spset2.bin sound\ggset1.bin \
sound\ggset2.bin sound\music01.bin sound\music02.bin sound\music03.bin \
sound\music04.bin sound\music05.bin sound\music06.bin sound\music07.bin \
sound\music08.bin sound\music09.bin sound\music10.bin sound\music11.bin \
sound\music12.bin sound\music13.bin sound\music14.bin sound\music17.bin \
sound\music18.bin sound\music18b.bin \
sound\music20.bin sound\music21.bin sound\music22.bin sound\music23.bin \
sound\music24.bin sound\music25.bin \
sound\sdgrd1.bin sound\sdgrd2.bin sound\sdgrd3.bin \
sound\sdend1.bin sound\sdspac.bin \
sound\sdinf.bin sound\sdcnt.bin sound\sdovr.bin \
sound\sddis.bin sound\sdtlk.bin \
sound\sdst1.bin sound\sdst2.bin \
sound\sdst3.bin sound\sdst4.bin sound\sdst5.bin sound\sdst6.bin \

