;	ษอออออออออออออออออออป
;	บ                   บ
;	บPlayer no parameterบ
;	บ                   บ
;	ศอออออออออออออออออออผ



;ษออออออออออออออป
;บsubmarine modeบ
;ศออออออออออออออผ

; weight in the sea.
; [ 0(karui)-255(omoi) ]
; normal = 30H

weight_isFOX		equ	30H
weight_isFALCO	equ	30H
weight_isSLIPPY	equ	60H
weight_isPEPPY	equ	60H
weight_isKANKICHI	equ	30H
weight_isYOSHI	equ	30H


