; #######################
; ## ROM Configuration ##
; #######################

;####################################################################################################################

; Cartridge Configuration

; PAL/NTSC (1/0)
pal					equ	0

; Run Super FX chip @ 21Mhz
fast				equ	1

; Super FX chip cache on/off
CacheOn				equ	1


; Game Language

; Switch between English (0) and Japanese (1)
janglish			equ	0

; German Version  (unused)
german				equ	0

; French Version  (unused)
french				equ	0


; Title Screen Copyright Year

kyear				equ	96	; 95/96/97/17 = 1995/1996/1997/2017

;####################################################################################################################
