	MSG	<PEPPER OTHER Star Fox, we have an emergency!>
	MSG	<PEPPER OTHER Andross is alive...>
	MSG	<PEPPER OTHER ...and he's launched an attack against Corneria!>
	MSG	<PEPPER OTHER Enemy forces have sortied from Andross' motherships and>
	MSG	<PEPPER OTHER carriers, and are heading towards Corneria.>
	MSG	<PEPPER OTHER They've also built bases on several planets,>
	MSG	<PEPPER OTHER and are firing IPBMs at Corneria.>
	MSG	<PEPPER OTHER Your help is crucial!>
	MSG	<PEPPER OTHER Corneria can take some hits,>
	MSG	<PEPPER OTHER but with excessive damage, we will fall!>
	MSG	<PEPPER OTHER Protect Corneria, and wipe out Andross' army!>
	MSG	<PEPPER OTHER We're counting on you, Star Fox!>
	MSG	<PEPPER OTHER Destroy the base from the inside!>
	MSG	<PEPPER OTHER Attack the carrier and destroy its core!>
	MSG	<PEPPER DOWN Corneria is taking damage!>
	MSG	<PEPPER DOWN Corneria is being attacked...!>
	MSG	<PEPPER DOWN There's no time! Hurry...!>
	MSG	<PEPPER DOWN Missiles...! What are you doing?!>
	MSG	<PEPPER DOWN Industrial blocks damaged by Planet Cannon fire!>
	MSG	<PEPPER OTHER Liberate the planets of the Lylat system!>
	MSG	<PEPPER OTHER The Mothership can warp to planets that don't have enemy bases.>
	MSG	<PEPPER OTHER Choose where the Arwing will be deployed with [(B)].>
	MSG	<ANDROSS OTHER I have returned to take my revenge!>
	MSG	<ANDROSS HELP Cornerian scum!>
	MSG	<ANDROSS DOWN You will soon bow before me!>
	MSG	<FOX OTHER You can boost with [(Y)]!>
	MSG	<FALCO OTHER Hit [(Y)] to accelerate!>
	MSG	<PEPPY OTHER [(Y)], lets you use the boost!>
	MSG	<SLIPPY OTHER Press [(Y)] for a speed boost, ribbit!>
	MSG	<GIRL1 OTHER You can boost while holding [(Y)]!>
	MSG	<GIRL2 OTHER Press [(Y)] to fly using the boost!>
	MSG	<FOX OTHER Pursue them with the [(Y)] boost!>
	MSG	<FALCO OTHER Don't doze off! Use the [(Y)] boost!>
	MSG	<PEPPY OTHER They're getting away! Use [(Y)] to boost!>
	MSG	<SLIPPY OTHER They're getting away, ribbit! Boost with [(Y)]>
	MSG	<GIRL1 OTHER They're getting away! Chase with the [(Y)] boost!>
	MSG	<GIRL2 OTHER Give chase with the [(Y)] boost!>
	MSG	<FOX OTHER Corneria's in danger! Let's retreat with [STRT]!>
	MSG	<FALCO OTHER Tch! ...let's go help them with [STRT]!>
	MSG	<PEPPY OTHER Let's head for Corneria! Use [STRT] to pull out!>
	MSG	<SLIPPY OTHER Gotta save Corneria! Let's go back with [STRT].>
	MSG	<GIRL1 OTHER That's not good! Let's scram with [STRT]!>
	MSG	<GIRL2 OTHER No...! Let's go with [STRT]!>
	MSG	<FOX OTHER There's no time! Hit [STRT]!>
	MSG	<FALCO OTHER This is bad! Hit [STRT] to go!>
	MSG	<PEPPY OTHER Not good! Use [STRT] to leave!>
	MSG	<SLIPPY OTHER We're in trouble! Retreat with [STRT]!>
	MSG	<GIRL1 OTHER Let's give up here for now! Push [STRT]!>
	MSG	<GIRL2 OTHER Time's up! We'll lose if you don't hit [STRT] now!>
	MSG	<FOX OTHER You're retreating from the battle. Go back!>
	MSG	<FALCO OTHER The battle's over there!>
	MSG	<PEPPY OTHER There's nothing here! Go back!>
	MSG	<SLIPPY OTHER Lost? It's this way, ribbit!>
	MSG	<GIRL1 OTHER I'm going back! This way!>
	MSG	<GIRL2 OTHER Nothing here. Let's go back...>
	MSG	<FOX OTHER You can transform with [SLCT]!>
	MSG	<FALCO OTHER [SLCT] transforms your Arwing!>
	MSG	<PEPPY OTHER You can change form if you hit [SLCT].>
	MSG	<SLIPPY OTHER [SLCT] transforms your Arwing, ribbit!>
	MSG	<GIRL1 OTHER If you want to transform, hit [SLCT]!>
	MSG	<GIRL2 OTHER When you hit [SLCT], your Arwing will transform!>
	MSG	<FOX OTHER Avoid the magma!>
	MSG	<FALCO OTHER Don't come crying if you get burned!>
	MSG	<PEPPY OTHER If you land on magma, you'll take damage!>
	MSG	<SLIPPY OTHER My body's all dried out! Hot, hot!>
	MSG	<GIRL1 OTHER The Arwings can't withstand magma!>
	MSG	<GIRL2 OTHER Be careful of the magma!>
	MSG	<FOX OTHER Look for the switch to open the gate!>
	MSG	<FALCO OTHER Find the switch to open the entrance!>
	MSG	<PEPPY OTHER We're getting nowhere. Gotta get inside!>
	MSG	<SLIPPY OTHER Look for the entrance switch, ribbit!>
	MSG	<GIRL1 OTHER This is pointless! We have to get inside!>
	MSG	<GIRL2 OTHER There must be a switch somewhere!>
	MSG	<FOX OTHER They've put up a barrier!>
	MSG	<FALCO OTHER We have to destroy the barrier generator!>
	MSG	<PEPPY OTHER If we don't destroy the barrier first...>
	MSG	<SLIPPY OTHER Destroy the barrier generator, ribbit!>
	MSG	<GIRL1 OTHER Gotta get through the barrier!>
	MSG	<GIRL2 OTHER Destroy the barrier's generator!>
	MSG	<PEPPER HELP A new squadron has sortied!>
	MSG	<PEPPER HELP An IPBM has been fired at Corneria!>
	MSG	<PEPPER HELP A new enemy carrier has appeared!>
	MSG	<PEPPER OTHER Be aware of Corneria's condition!>
	MSG	<FOX OTHER >
	MSG	<ANDROSS OTHER I'm gonna give you punks a good thrashing!>
	MSG	<PEPPER OTHER Well done! That ought to stop the missile attacks.>
	MSG	<ANDROSS HELP Getting in my way again...>
	MSG	<ANDROSS DOWN Gwaaargh! What is he DOING?!>
	MSG	<PEPPER OTHER Good! That ought to slow them down.>
	MSG	<FOX OTHER Continue with your wingman?>
	MSG	<FOX OTHER Yes>
	MSG	<FOX OTHER No>
	MSG	<PEPPER OTHER The Satellite Defense System.>
	MSG	<PEPPER OTHER The Satellite System has been captured! Recover it!>
	MSG	<FOX OTHER MISSION>
	MSG	<FOX OTHER RECORD>
	MSG	<FOX OTHER TEST>
	MSG	<FOX OTHER TRAINING>
	MSG	<FOX OTHER CONFIG>
	MSG	<FOX OTHER STEREO>
	MSG	<FOX OTHER MONO>
	MSG	<FOX OTHER NORMAL>
	MSG	<FOX OTHER HARD>
	MSG	<FOX OTHER EXPERT>
	MSG	<FOX OTHER Move?                              Yes                  No>
	MSG	<FOX OTHER Deploy the Mothership.>
	MSG	<PEPPER OTHER Good work!>
	MSG	<FOX OTHER [RARR]>
	MSG	<PEPPER OTHER Return to the Mothership to restore your shields.>
	MSG	<PEPPER DOWN Gwaaaaaaah! It's all over!>
	MSG	<ANDROSS OTHER Looks like some rats are slipping through... Heh...>
	MSG	<ANDROSS HELP I'll go easy on you! Gahahaha!>
	MSG	<ANDROSS OTHER Gahahaha! How entertaining!>
	MSG	<ANDROSS DOWN Launch the IPBMs at Corneria!>
	MSG	<ANDROSS HELP They're in the Planet Cannon's range! Gahaha!>
	MSG	<ANDROSS DOWN Fire the Planet Cannon!>
	MSG	<ANDROSS OTHER I'm just getting started!>
	MSG	<ANDROSS HELP Ho ho, don't get too cocky...>
	MSG	<ANDROSS DOWN Playtime's over! Crush them!>
	MSG	<ANDROSS DOWN Impressive show! Let me thank you...>
	MSG	<ANDROSS HELP Head for Corneria, and ready the Planet Cannon!>
	MSG	<FOX OTHER You can boost with [(X)]!>
	MSG	<FALCO OTHER The Arwing's boost is [(X)]!>
	MSG	<PEPPY OTHER You'll accelerate while pressing [(X)]!>
	MSG	<SLIPPY OTHER Boost while pressing [(X)], ribbit!>
	MSG	<GIRL1 OTHER You can boost while pressing [(X)]!>
	MSG	<GIRL2 OTHER You fly faster while pressing [(X)]!>
	MSG	<FOX OTHER Pursue with the [(X)] boost!>
	MSG	<FALCO OTHER Slowpoke! Use the [(X)] boost!>
	MSG	<PEPPY OTHER Use the [(X)] boost to catch up!>
	MSG	<SLIPPY OTHER They're getting away! Accelerate with [(X)]-crrroak!>
	MSG	<GIRL1 OTHER Chase them using the [(X)] boost!>
	MSG	<GIRL2 OTHER Give chase with the [(X)] boost!>
	MSG	<ANDROSS OTHER Hehehe... You've got spirit!>
	MSG	<PEPPER HELP Caught the Planet Cannon's Energy Charge!>
	MSG	<PEPPER OTHER The Planet Cannon is charging! Take it down!>
	MSG	<ANDROSS OTHER Admirable, Star Fox!>
	MSG	<ANDROSS OTHER You've gotten better, Star Fox.>
	MSG	<ANDROSS OTHER You've finally come this far...>
	MSG	<ANDROSS HELP Impressive! But you die here!>
	MSG	<ANDROSS HELP Pepper's dogs...!>
	MSG	<ANDROSS HELP You're ALWAYS getting in my way!! >
	MSG	<ANDROSS DOWN Suffer!!>
	MSG	<ANDROSS DOWN Time for my revenge!>
	MSG	<ANDROSS DOWN Don't worry, I'll go easy!>
	MSG	<FOX OTHER The missiles are falling!>
	MSG	<FALCO OTHER Those damn missiles...!>
	MSG	<PEPPY OTHER Missiles are falling on Corneria!>
	MSG	<SLIPPY OTHER Missiles dropping to Corneria, ribbit!>
	MSG	<GIRL1 OTHER Eeek! missiles are falling on Corneria!>
	MSG	<GIRL2 OTHER No! The missiles are falling on Corneria!>
	MSG	<FOX OTHER Great! No more missiles will be fired from here!>
	MSG	<FALCO OTHER Piece of cake!>
	MSG	<PEPPY OTHER Alright! That's this planet!>
	MSG	<SLIPPY OTHER Hooray! No more missiles from here!>
	MSG	<GIRL1 OTHER Yeeeeeeehaw!>
	MSG	<GIRL2 OTHER Our missile problems just got lighter!>
	MSG	<FOX OTHER Battleship destroyed!>
	MSG	<FALCO OTHER The bigger they are...>
	MSG	<PEPPY OTHER That'll make things easier!>
	MSG	<SLIPPY OTHER An easy victory, ribbit!>
	MSG	<GIRL1 OTHER Scratch one!>
	MSG	<GIRL2 OTHER That'll reduce their forces!>
	MSG	<WOLF DOWN Noooo! Star Fox...!>
	MSG	<CHAMELEON DOWN Gaaah! Wolf, I leave the rest to you!>
	MSG	<PIG DOWN Beaten by these punks...! I've gotten rusty...>
	MSG	<MONKEY DOWN Arrghh! I'll remember this...!>
	MSG	<WOLF DOWN I'll pay you back for this!>
	MSG	<CHAMELEON OTHER That's far enough! Leon of Star Wolf is here!>
	MSG	<PIG OTHER I'm Pigma of Star Wolf! Prepare yourself!>
	MSG	<MONKEY OTHER I'm Algy, I won't just let you do what you want!>
	MSG	<WOLF OTHER Detestable punks!>
	MSG	<CHAMELEON OTHER So you're Wolf's targets... Time to die!>
	MSG	<PIG OTHER Andross paid good cash for such an easy job!>
	MSG	<MONKEY OTHER Our boss said you were nothing special!>
	MSG	<WOLF OTHER Brats! Time for punishment!>
	MSG	<PEPPER OTHER The Satellite System has been captured! Recover it!>
	MSG	<WOLF OTHER Time to end our rivalry!>
	MSG	<CHAMELEON OTHER Not bad, Star Fox! But I won't lose!>
	MSG	<PIG OTHER That was just the beginning!>
	MSG	<MONKEY OTHER I won't let you off so easy!>
	MSG	<WOLF OTHER I, Wolf, won't let you go any further!>
	MSG	<FOX OTHER Phew, we did it!>
	MSG	<FALCO OTHER Hmph! No big deal..>
	MSG	<PEPPY OTHER Are you okay? That was close!>
	MSG	<SLIPPY OTHER That was a close one, ribbit!>
	MSG	<GIRL1 OTHER Toughie, eh?>
	MSG	<GIRL2 OTHER Phew, that was close!>
	MSG	<FOX SPECIAL We're okay!>
	MSG	<FALCO SPECIAL Hmph! An easy victory!>
	MSG	<PEPPY SPECIAL No need to worry!>
	MSG	<SLIPPY SPECIAL My heart was pounding too, ribbit!>
	MSG	<GIRL1 SPECIAL What are you talking about!? Pah!>
	MSG	<GIRL2 SPECIAL Huh? I was totally composed!>
	MSG	<PEPPER OTHER Use the Mothership to recover and warp.>
	MSG	<PEPPER DOWN The Satellite is attacking Corneria! Hurry!>
	MSG	<PEPPER OTHER The Satellite System shot down the enemy.>
	MSG	<FOX OTHER Tap [(L)] or [(R)] twice to barrel roll!>
	MSG	<FALCO OTHER Tap [(L)] or [(R)] twice to barrel roll!>
	MSG	<PEPPY OTHER Tap [(L)] or [(R)] twice! Roll and reflect!>
	MSG	<SLIPPY OTHER Tap [(L)] or [(R)] twice to reflect enemy lasers!>
	MSG	<GIRL1 OTHER Tap [(L)] or [(R)] twice to roll and reflect!>
	MSG	<GIRL2 OTHER Tap [(L)] or [(R)] twice to reflect enemy lasers!>
	MSG	<PEPPER OTHER I'll explain the Walker's controls.>
	MSG	<PEPPER OTHER Use [DPAD] to move, and turn with [(L)] and [(R)].>
	MSG	<PEPPER OTHER You can accelerate by tapping [DPAD] twice.>
	MSG	<PEPPER OTHER Jump with [(Y)]. [SLCT] changes forms.>
	MSG	<PEPPER OTHER Use the Arwing's transformation wisely!>
	MSG	<PEPPER HELP The Satellite System was captured! Recover it!>
	MSG	<PEPPER OTHER With this, most of Andross' forces have been swept away.>
	MSG	<PEPPER OTHER We've got him right where we want him!>
	MSG	<PEPPER OTHER You can change to your wingman if you press [SLCT].>
	MSG	<PEPPER OTHER Jump with [(B)]. [SLCT] changes forms.>
	MSG	<PEPPER OTHER Blaster leveled up - now it homes in!>
	MSG	<PEPPER OTHER Use the target marker to lock on, then fire!>
	MSG	<PEPPER OTHER A secret base... Go on in.>