	MSG	<pepper OTHER [St][ar] [Fo]x te[am]-[do] [yo]u [re]ad [me]? I [ha][ve] t[er][ri][bl]e [ne]ws.>
	MSG	<pepper OTHER O[ur] swo[rn] [en][em]y, [th]e [fi][en]d [An][dr]o[ss], [is] [al]i[ve]!>
	MSG	<pepper OTHER Ev[en] [as] [we] [sp]eak, [he] [is] la[un][ch][in]g [an] [as][sa][ul]t [on] [Co][rn][er][ia].>
	MSG	<pepper OTHER [Th]e B[at]t[le] C[ar][ri][er]s [an]d [at][ta][ck] f[or][ce]s [of] [An][dr]o[ss]>
	MSG	<pepper OTHER [ar]e n[ow] adv[an]c[in]g [on] [Co][rn][er][ia].>
	MSG	<pepper OTHER [En][em]y [ba][se]s [ha][ve] [be][en] es[ta][bl][is][he]d [on] [ov][er]r[un] [pl][an][et]s.>
	MSG	<pepper OTHER [Pl][an][et][ar]y [mi][ss]i[le]s [wi][ll] [be] [fi][re]d [fr][om] [th]e[se] [en][em]y [ba][se]s.>
	MSG	<pepper OTHER On[ce] [ag]a[in], [we] [mu][st] [as]k [yo]u [fo]r [yo][ur] a[ss][is][ta]n[ce], S[ta]r [Fo]x.>
	MSG	<pepper OTHER [Co][rn][er][ia] [wi][ll] [su]r[vi][ve] [if] [it] [su]s[ta][in]s [mi][no]r [da][ma][ge], but [if]>
	MSG	<pepper OTHER [da][ma][ge] [re]a[ch]es 100 p[er][ce]nt, [it] [is] [al]l [ov][er].>
	MSG	<pepper OTHER [En][ga][ge] [th]e [fo]r[ce]s [of] [An][dr]o[ss] [wh]i[le] [at] [th]e [sa][me] [ti][me] [ke]ep[in]g>
	MSG	<pepper OTHER [da][ma][ge] [to] [Co][rn][er][ia] [at] [th]e lo[we][st] [le][ve]l [po][ss]ib[le]. Go[od] Lu[ck]!>
	MSG	<pepper OTHER Y[ou] [mu][st] [in][fi]l[tr][at]e [th]e [en][em]y [ba][se] [an]d [an]nihil[at]e [it].>
	MSG	<pepper OTHER F[ly] [in][to] [th]e B[at]t[le] C[ar][ri][er] [an]d [de][st]roy [it]s [en][er]gy c[or]e.>
	MSG	<pepper down [Co][rn][er][ia] [is] n[ow] [un]d[er] [as][sa][ul]t!>
	MSG	<pepper down [Co][rn][er][ia] [is] [un]d[er] di[re][ct] [en][em]y [at][ta][ck]! [He]lp [us]...>
	MSG	<pepper down [En][em][ie]s [at][ta][ck][in]g [Co][rn][er][ia]...[de]f[en][se]s [we]ak[en][in]g...>
	MSG	<pepper down [We] [ha][ve] [be][en] h[it] [by] a [pl][an][et][ar]y [mi][ss]i[le]!>
	MSG	<pepper down [Th]e [Pl][an][et] C[an]n[on] [ha]s [ca][us][ed] [he]avy [da][ma][ge] [he][re]!>
	MSG	<pepper OTHER [To] [en][ga][ge] [th]e [en][em]y, l[an]d [on] [pl][an][et]s [an]d [in]t[er][ce]pt [sh][ip]s.>
	MSG	<pepper OTHER R[et][ur]n [to] [yo][ur] Mo[th][er][sh][ip] [to] w[ar]p [to] [an]y [fr]ee [pl][an][et].>
	MSG	<pepper OTHER Se[le][ct] a [de][st][in][at]i[on] [by] m[ov][in]g [th]e c[ur]s[or], [th][en] p[re][ss] [(B)].>
	MSG	<ANDROSS OTHER I [ha][ve] [re][tu][rn][ed]! I [sh][al]l [ma][ke] [th]e [Co][rn][er][ia]ns [su]ff[er]!>
	MSG	<andross help In[ha]b[it][an]ts [of] [Co][rn][er][ia]-[yo]u [sh][al]l fe[ar] my v[en][ge][an][ce].>
	MSG	<andross down I [wi][ll] [de]m[on][st]r[at]e my a[we][so][me] [po][we]r [on] [al]l [of] Lyl[at]!>
	MSG	<FOX OTHER D[on]['t] [fo]r[ge]t [to] p[re][ss] [(Y)] [to] [fi][re] [yo][ur] [bo]o[st][er]s!>
	MSG	<FALCO OTHER [Yo][ur] [bo]o[st][er]s [ar]e a[ct]iv[at][ed] [by] p[re][ss][in]g [(Y)].>
	MSG	<PEPPY OTHER By p[re][ss][in]g [(Y)], [yo]u c[an] [bo]o[st] [yo][ur] [sp]e[ed].>
	MSG	<SLIPPY OTHER F[ly] [fa][st][er] [by] p[re][ss][in]g-[ri][bb][it]!- [(Y)].>
	MSG	<GIRL1 OTHER [If] [yo]u w[an]t [to] [sp]e[ed] [up], u[se] [(Y)].>
	MSG	<GIRL2 OTHER P[re][ss] [(Y)] [an]d [yo]u [wi][ll] a[ct]iv[at]e [yo][ur] [bo]o[st][er]s!>
	MSG	<FOX OTHER Boo[st] [yo][ur] [sp]e[ed] [an]d [ch]a[se] [do][wn] [en][em][ie]s [wi][th] [(Y)]!>
	MSG	<FALCO OTHER Y[ou]'[re] f[ly][in]g [to]o sl[ow]! U[se] [(Y)] [to] [sp]e[ed] [up].>
	MSG	<PEPPY OTHER [We]'[re] [fa][ll][in]g [be]h[in]d. P[re][ss] [(Y)] [to] [bo]o[st] [sp]e[ed]!>
	MSG	<SLIPPY OTHER [Th][ey]'[re] [ge][tt][in]g [aw][ay]! P[re][ss] [(Y)]- [rr]r[ri][bb][it]!>
	MSG	<GIRL1 OTHER [Th][ey] [ar]e es[ca]p[in]g! C[at][ch] [th]e [en][em]y [by] p[re][ss][in]g [(Y)]!>
	MSG	<GIRL2 OTHER [If] [we] d[on]['t] [bo]o[st] o[ur] [sp]e[ed] [wi][th] [(Y)], [th][ey]'[ll] [ge]t [aw][ay]!>
	MSG	<FOX OTHER [Co][rn][er][ia] [is] [un]d[er] [at][ta][ck]. H[it] [(ST][NOSP][AR][NOSP][T)]!>
	MSG	<FALCO OTHER H[ey]! [We] [mu][st] [ge]t [ba][ck] [to] [Co][rn][er][ia]. P[re][ss] [(ST][NOSP][AR][NOSP][T)].>
	MSG	<PEPPY OTHER [We] [ha][ve] [go]t [to] [re][tu][rn] [to] [Co][rn][er][ia]! P[re][ss] [(ST][NOSP][AR][NOSP][T)].>
	MSG	<SLIPPY OTHER [Th][er]e's [tr][ou]b[le] [ba][ck] [at] [Co][rn][er][ia]! P[re][ss] [(ST][NOSP][AR][NOSP][T)].>
	MSG	<GIRL1 OTHER Oh, oh! [Co][rn][er][ia] [is] [in] [tr][ou]b[le]. P[re][ss] [(ST][NOSP][AR][NOSP][T)] [to] [re][tu][rn].>
	MSG	<GIRL2 OTHER So[me][th][in]g's [up] [at] [Co][rn][er][ia]. P[re][ss] [(ST][NOSP][AR][NOSP][T)]!>
	MSG	<FOX OTHER [Th][is] [is] [ta]k[in]g [to]o l[on]g. P[re][ss] [(ST][NOSP][AR][NOSP][T)].>
	MSG	<FALCO OTHER L[et]'s [ge]t [ou]t [of] [he][re]! P[re][ss] [(ST][NOSP][AR][NOSP][T)].>
	MSG	<PEPPY OTHER It's [no] [go][od]! [To] [ge]t [ou]t [of] [he][re], p[re][ss] [(ST][NOSP][AR][NOSP][T)].>
	MSG	<SLIPPY OTHER [We]'[re] [wa][st][in]g [ti][me] [he][re]. P[re][ss] [(ST][NOSP][AR][NOSP][T)]-c[rr]roak!>
	MSG	<GIRL1 OTHER L[et]'s [ba]g [th][is]. [We] [to]ok [to]o l[on]g. P[re][ss] [(ST][NOSP][AR][NOSP][T)].>
	MSG	<GIRL2 OTHER Ti[me] [is] lim[it][ed], [so] [le]t's gi[ve] [th][is] [up]. P[re][ss] [(ST][NOSP][AR][NOSP][T)].>
	MSG	<FOX OTHER [We]'[ve] [le]ft [th]e b[at]t[le][fi]e[ld]. [Fo][ll][ow] [me] [ba][ck]!>
	MSG	<FALCO OTHER O[ur] b[at]t[le] [si]te [is] [ba][ck] [th][er]e. I'[ll] [le]ad [us] [ba][ck].>
	MSG	<PEPPY OTHER H[ey], [th][er]e's [no] [on]e [ou]t [he][re]! [Fo][ll][ow] [me] [ba][ck]!>
	MSG	<SLIPPY OTHER [We] [ma]y [be] lo[st]. I [th][in]k [we] [sh][ou][ld] [go] [ba][ck]. [Fo][ll][ow] [me]!>
	MSG	<GIRL1 OTHER [We] [sh][ou][ld] [re][tu][rn] [an]d [at][ta][ck] [th]e [en][em]y. [Fo][ll][ow] [me]!>
	MSG	<GIRL2 OTHER [Th][er]e [ar]e [no] [en]e[mi]es [ou]t [he][re]. [Co][me] [wi][th] [me]!>
	MSG	<FOX OTHER R[em][em]b[er], p[re][ss] [(SE][NOSP][LE][NOSP][CT)] [in] [or]d[er] [to] [tr][an]s[fo][rm].>
	MSG	<FALCO OTHER P[re][ss] [(SE][NOSP][LE][NOSP][CT)] [if] [yo]u w[an]t [to] [tr][an]s[fo][rm]!>
	MSG	<PEPPY OTHER Tr[an]s[fo][rm] [yo][ur] [sh][ip] [by] p[re][ss][in]g [(SE][NOSP][LE][NOSP][CT)].>
	MSG	<SLIPPY OTHER D[on]['t] [fo]r[ge]t,  p[re][ss] [(SE][NOSP][LE][NOSP][CT)] [to] [tr][an]s[fo][rm]!>
	MSG	<GIRL1 OTHER [If] [yo]u w[an]t [to] [tr][an]s[fo][rm], p[re][ss] [(SE][NOSP][LE][NOSP][CT)]!>
	MSG	<GIRL2 OTHER P[re][ss] [(SE][NOSP][LE][NOSP][CT)], [an]d [yo][ur] [sh][ip] [wi][ll] [tr][an]s[fo][rm]!>
	MSG	<FOX OTHER [Co]u[ti][on]! L[an]d[in]g [on] M[ag][ma] [ca]u[se]s [da][ma][ge].>
	MSG	<FALCO OTHER D[on]['t] l[an]d! Y[ou] [ta][ke] [da][ma][ge] [wh]i[le] [on] [th]e s[ur][fa][ce].>
	MSG	<PEPPY OTHER [Th]e s[ur][fa][ce] [of] M[ag][ma] [is] bu[rn][in]g hot! D[on]['t] l[an]d.>
	MSG	<SLIPPY OTHER Hot! Hot! Hot! I'm [dr]y[in]g [ou]t! D[on]['t] l[an]d-[ri][bb][it].>
	MSG	<GIRL1 OTHER [Th]e s[ur][fa][ce] [is] molt[en]! D[on]['t] l[an]d, ok[ay]?>
	MSG	<GIRL2 OTHER W[at][ch] [it]! Y[ou] [ta][ke] [da][ma][ge] [if] [yo]u l[an]d [on] M[ag][ma].>
	MSG	<FOX OTHER At[ta][ck][in]g [fr][om] [he][re] [is] [no] [go][od]. F[in]d a sw[it][ch].>
	MSG	<FALCO OTHER [We] [ne][ed] [to] [fi]nd a sw[it][ch] [to] op[en] [th]e [en][tr][an][ce].>
	MSG	<PEPPY OTHER At[ta][ck]s [fr][om] [ou]t- [si][de] [ar]e u[se][le][ss]. A[ct]iv[at]e a sw[it][ch].>
	MSG	<SLIPPY OTHER [We] [mu][st] f[in]d a sw[it][ch] [th][at] op[en]s [an] [en][tr][an][ce].>
	MSG	<GIRL1 OTHER Ext[er]n[al] [at][ta][ck]s [ar]e i[ne]ffe[ct]i[ve]. F[in]d a sw[it][ch].>
	MSG	<GIRL2 OTHER [Th][er]e [is] a sw[it][ch] [so][me][pl]a[ce] [th][at] op[en]s [th]e [en][tr][an][ce].>
	MSG	<FOX OTHER [Th][er]e's a b[ar][ri][er]! K[no][ck] [ou]t [th]e [sh][ie][ld] g[en][er][at][or]s.>
	MSG	<FALCO OTHER De[st]roy [th]e [sh][ie][ld] g[en][er][at][or]s, [th][en] [st][ar]t [th]e [as][sa][ul]t!>
	MSG	<PEPPY OTHER B[ar][ri][er] [de]te[ct][ed]. F[in]d [an]d [de][st]roy [it]s p[ow][er] [so][ur][ce].>
	MSG	<SLIPPY OTHER A [sh][ie][ld] g[en][er][at][or] [is] [he][re] [so][me]w[he][re]. De[st]roy [it]-[ri][bb][it]!>
	MSG	<GIRL1 OTHER Cut [of]f p[ow][er] [to] [th]e b[ar][ri][er], [th][en] [at][ta][ck] [th]e [ta]rg[et].>
	MSG	<GIRL2 OTHER [Th][er]e's a [sh][ie][ld]! [We] [mu][st] [de][st]roy [it]s g[en][er][at][or]s.>
	MSG	<pepper help A B[at]t[le] C[ar][ri][er] [ha]s la[un][ch][ed] [an] [at][ta][ck] [fo]r[ce].>
	MSG	<pepper help W[ar]n[in]g! [Pl][an][et][ar]y [mi][ss]i[le] [he]ad[ed] [fo]r [Co][rn][er][ia]!>
	MSG	<pepper help Em[er]g[en]cy! A [ne]w B[at]t[le] C[ar][ri][er] [ha]s sudd[en][ly] appe[ar][ed].>
	MSG	<pepper OTHER Keep [an] [ey]e [on] [th]e [da][ma][ge] [do][ne] [to] [Co][rn][er][ia].>
	MSG	<FOX OTHER >
	MSG	<ANDROSS OTHER Sh[ow] [no] m[er]cy. Cru[sh] [th][em] [by] [an]y [me][an]s [po]s[si]b[le].>
	MSG	<pepper OTHER [We][ll] [do][ne]! M[is][si][le] [at][ta][ck]s [fr][om] [th][at] [pl][an][et] [ha][ve] [en]d[ed].>
	MSG	<ANDROSS help S[ta]r [Fo]x, [yo]u m[an]gy c[ur], h[ow] [da][re] [yo]u c[ha][ll][en][ge] [me] a[ga][in]?>
	MSG	<ANDROSS down G[wa]rg!! Y[ou] p[at]h[et]ic [fo]ols [ar]e comp[le]te[ly] w[or][th][le][ss]!>
	MSG	<pepper OTHER Go[od] [sh][ow]! N[ow] [we] c[an] expe[ct] few[er] [at][ta][ck]s.>
	MSG	<FOX OTHER C[on]t[in]ue [as] [wi]ng m[an]?>
	MSG	<FOX OTHER Yes>
	MSG	<FOX OTHER No>
	MSG	<pepper OTHER [Th][is] [is] o[ur] S[at]e[ll][it]e Def[en][se] [Pl][at][fo][rm]. It prote[ct]s [Co][rn][er][ia].>
	MSG	<pepper OTHER [Th]e s[at]e[ll][it]e [ha]s [be][en] [ca]pt[ur][ed]! Y[ou] [mu][st] lib[er][at]e [it].>
	MSG	<FOX OTHER MISSION>
	MSG	<FOX OTHER RECORD>
	MSG	<FOX OTHER TEST>
	MSG	<FOX OTHER TRAINING>
	MSG	<FOX OTHER CONFIG>
	MSG	<FOX OTHER STEREO>
	MSG	<FOX OTHER MONO>
	MSG	<FOX OTHER NORMAL>
	MSG	<FOX OTHER HARD>
	MSG	<FOX OTHER EXPERT>
	MSG	<FOX OTHER W[ar]p [vi]a [yo][ur] Mo[th][er][sh][ip]?     Yes                 No>
	MSG	<FOX OTHER [Pl]a[ce] [th]e c[ur]s[or] [on] [yo][ur] [de][st][in][at]i[on] [an]d p[re][ss] [(B)].>
	MSG	<pepper OTHER Y[ou] [re][ca]pt[ur][ed] [th]e s[at]e[ll][it]e [pl][at][fo][rm]. Incr[ed]ib[le] job!>
	MSG	<FOX OTHER [RARR]>
	MSG	<pepper OTHER [Yo][ur] [sh][ip]'s [sh][ie][ld]s [ar]e [re][ch][ar]g[ed] [at] [yo][ur] Mo[th][er][sh][ip].>
	MSG	<pepper down Ayaah! It's [al]l [ov][er]! [Co][rn][er][ia] [is] [fi]ni[sh][ed]!>
	MSG	<ANDROSS OTHER It appe[ar]s a p[un]y p[et] r[at] [is] r[un]n[in]g ab[ou]t...h[ow] cute!>
	MSG	<ANDROSS help Go [pl][ay] [wi][th] [yo][ur] p[et]. Ju[st] [pl][ay] ni[ce]...G[wa]h [ha] [ha]!>
	MSG	<ANDROSS OTHER G[ar]g gya [ha] [ha]! It's [no] f[un] [wh][en] [th][er]e's [no] [re][si][st][an][ce].>
	MSG	<ANDROSS down La[un][ch] [pl][an][et][ar]y m[is][si][le]s [at] [Co][rn][er][ia]!>
	MSG	<ANDROSS help [Co][rn][er][ia]'s [wi][th][in] r[an][ge] [of] [th]e [Pl][an][et] C[an]n[on]! Gw[ar]g [ha] [ha]!>
	MSG	<ANDROSS down [Th][is] [is] [me][an]t [fo]r [yo]u [al][on]e. [Pl][an][et] C[an]n[on] ...FIRE!!>
	MSG	<ANDROSS OTHER Hmm...[yo]u did [we][ll], but [th]e [re][al] b[at]t[le] [ha]sn['t] ev[en] [be]g[un].>
	MSG	<ANDROSS help Hy[or]g! Hy[or]g! Hy[or]g! [If] [yo]u [th][in]k [yo]u [do] [we][ll], [yo]u [ar]e a [fo]ol!>
	MSG	<ANDROSS down [Pl][ay] [ti][me] [is] [ov][er]! De[st]roy [th]e [we]akl[in]gs!>
	MSG	<ANDROSS down Y[ou]'[ve] [su]rpr[is][ed] [me]. H[er]e [is] [yo][ur] [re]w[ar]d [fo]r [am][us][in]g [me].>
	MSG	<ANDROSS help B[at]t[le] C[ar][ri][er]s! On [to] [Co][rn][er][ia]! P[re]p[ar]e [th]e [Pl][an][et] C[an]n[on]!>
	MSG	<FOX OTHER Boo[st] [yo][ur] [sp]e[ed] [by] p[re][ss][in]g [(X)]. D[on]['t] [fo]rg[et]!>
	MSG	<FALCO OTHER [Th]e [(X)] bu[tt][on] ac[ti]v[at]es [yo][ur] [bo]o[st][er]s!>
	MSG	<PEPPY OTHER U[se] [(X)] [to] [bo]o[st] [yo][ur] [sp]e[ed]!>
	MSG	<SLIPPY OTHER P[re][ss][in]g [(X)] [ma][ke]s [yo]u f[ly] [fa][st][er]! R[rr][ri][bb][it]!>
	MSG	<GIRL1 OTHER [To] [sp]e[ed] [up], p[re][ss] [(X)] [to] a[ct]iv[at]e [bo]o[st][er]s!>
	MSG	<GIRL2 OTHER Y[ou] c[an] [bo]o[st] [yo][ur] [sp]e[ed] [by] [us][in]g [(X)]!>
	MSG	<FOX OTHER C[ha][se] [th]e [en][em]y [do][wn] [wi][th] [(X)]!>
	MSG	<FALCO OTHER Y[ou]'[re] f[ly][in]g [to]o sl[ow]! U[se] [(X)] [to] [bo]o[st] [sp]e[ed].>
	MSG	<PEPPY OTHER [Th]e [en][em]y [is] w[ay] ahead [of] [us]. U[se] [(X)] [to] [sp]e[ed] [up]!>
	MSG	<SLIPPY OTHER [Th][ey]'[re] [ge][tt][in]g [aw][ay]! Boo[st] [sp]e[ed] [wi][th] [(X)]-c[rr]roak!>
	MSG	<GIRL1 OTHER [We]'[re] f[ar] [be]h[in]d! C[at][ch] [up] [by] [us][in]g [(X)]!>
	MSG	<GIRL2 OTHER Y[ou]'[ll] [ha][ve] [to] u[se] [(X)] [to] [ch]a[se] [th]e [en][em]y [do][wn].>
	MSG	<ANDROSS OTHER Ah! So [yo][ur] [re][so]l[ve] [is] [st]r[on]g! N[ow] [it]'s [ti][me] [to] g[et] [se][ri]o[us].>
	MSG	<pepper help A Pl[an][et] C[an][no]n's [ch][ar]g[in]g. [Yo]u [mu][st] [at][ta][ck] [th]e [ca][rr]i[er]!>
	MSG	<pepper OTHER [Th]e [en][em]y's [ch][ar]g[in]g [th]e [Pl][an][et] C[an]n[on]! De[st]roy [th][em] qui[ck][ly]!>
	MSG	<ANDROSS OTHER Not [ba]d...[no]t [ba]d [at] [al]l, [St][ar] [Fo]x.>
	MSG	<ANDROSS OTHER Y[ou] [ar]e impr[ov][in]g, [St][ar] [Fo]x.>
	MSG	<ANDROSS OTHER So, [yo]u [ma][de] [it] [th][is] f[ar]. I'[ve] [be][en] [wa][it][in]g [fo]r [yo]u.>
	MSG	<ANDROSS help Imp[re][ss]i[ve]!-but [yo][ur] ex[is]t[en][ce] [en]ds [he][re].>
	MSG	<ANDROSS help Y[ou] [ar]e ju[st] a p[up]p[et] [of] [th][at] [fo]ol Pepp[er]!>
	MSG	<ANDROSS help Y[ou]'[ve] [in]t[er]f[er][ed] [fo]r [th]e la[st] [ti][me], [Co][rn][er]i[an] [do]gs!>
	MSG	<ANDROSS down I [wi][ll] put [yo]u [to] [re][st]. D[on]['t] wo[rr]y- [it] [wi][ll] [be] qui[ck].>
	MSG	<ANDROSS down I [ha][ve] [no]t y[et] [fo]r[go][tt][en] [wh][at] [yo]u did [to] [me] [be][fo][re].>
	MSG	<ANDROSS down Ev[er]y[th][in]g [is] [in] my c[on][tr]ol! In [th]e [en]d, [yo]u'[ll] [we]ep.>
	MSG	<FOX OTHER [Th][er]e [is] a m[is][si][le] [he]ad[in]g [to]w[ar]d [Co][rn][er][ia]! S[to]p [it]!>
	MSG	<FALCO OTHER Ah [ha]! A m[is][si][le] [ha]s [be][en] la[un][ch][ed]! L[et]'s [de][st]roy [it]!>
	MSG	<PEPPY OTHER A m[is][si][le]'s [be][en] [si]ght[ed] [he]ad[in]g [fo]r [Co][rn][er][ia]!>
	MSG	<SLIPPY OTHER Ri[bb][it]! [Th][er]e's a m[is][si][le] [he]ad[ed] [fo]r [Co][rn][er][ia]!>
	MSG	<GIRL1 OTHER Y[ow]! [Co][rn][er][ia]'s [be][en] [ta]rg[et][ed] [by] a m[is][si][le]!>
	MSG	<GIRL2 OTHER Em[er]g[en]cy! M[is][si][le] [he]ad[ed] [fo]r [Co][rn][er][ia]!>
	MSG	<FOX OTHER [Th][at] [sh][ou][ld] [st]op  m[is][si][le]s co[mi]ng [fr][om] [th][at] [pl][an][et]!>
	MSG	<FALCO OTHER Ha! [An][dr]o[ss]'s [ba][se]s [ar]e [no][th][in]g!>
	MSG	<PEPPY OTHER A[ll] [ri]ght! No mo[re] m[is][si][le]s [fr][om] [th][at] [pl][an][et]!>
	MSG	<SLIPPY OTHER [We] did [it]! [Th]e [ba][se] [an]d [it]s m[is][si][le]s [ar]e [go][ne]!>
	MSG	<GIRL1 OTHER Ha, [ha], [ha]! [Th][at] [ba][se] w[as]n['t] [to]o [to]ugh!>
	MSG	<GIRL2 OTHER No [ba][se] [me][an]s [no] mo[re] m[is][si][le]s [fr][om] [th][at] [pl][an][et]!>
	MSG	<FOX OTHER Ok[ay]! [We] [to]ok [it] [ou]t! N[ow] o[ur] job [is] ea[si][er].>
	MSG	<FALCO OTHER It w[as] big, but [it] w[as]n['t] [to]o [to]ugh [fo]r [us]!>
	MSG	<PEPPY OTHER [Th][at] w[as] a [ma]j[or] [bl][ow] [to] [th]e [en][em]y!>
	MSG	<SLIPPY OTHER [Th]e B[at]t[le] C[ar][ri][er] w[as] [no]t [so] [ba]d. L[et]'s mo[ve] [on]!>
	MSG	<GIRL1 OTHER De[st]roy[in]g [th]e c[ar][ri][er] [de][st]roys [th]e [fi]ght[er]s, [to]o!>
	MSG	<GIRL2 OTHER O[ur] job [is] ea[si][er] [on][ce] [we] [de][st]roy [th]e c[ar][ri][er]s.>
	MSG	<wolf down I'm imp[re][ss][ed], [St][ar] [Fo]x. Y[ou] [ar]e t[al][en]t[ed]...>
	MSG	<chameleon down Yi[ke]s! Cap'n [Wo][lf] [is] g[on]na [ha][ve] [to] [de][al] [wi][th] y[ou]!>
	MSG	<pig down Un[be]l[ie]vab[le]! I [mu][st] [be] [ge][tt][in]g o[ld] [or] [so][me][th][in]g!>
	MSG	<monkey down Aaa[ar]gh! [We] w[on]['t] [fo]rg[et] [th][is]! Nooo!>
	MSG	<wolf down [To][da]y, I lo[se]. But [to]mo[rr][ow] I [sh]a[ll] cru[sh] [yo]u!>
	MSG	<chameleon OTHER Ha! Le[on] [of] [th]e [St][ar] [Wo][lf] [wi]ng [is] [no]w [he][re]!>
	MSG	<pig OTHER I'm Pig[ma] [of] [th]e [St][ar] [Wo][lf] [wi]ng! Beho[ld] my [ta]l[en]t!>
	MSG	<monkey OTHER My na[me] [is] Algy, [an]d I o[wn] [yo]u. [Co][me] [on]!>
	MSG	<wolf OTHER Pepp[er] [de][ce]iv[ed] [yo]u. I [am] [th]e [be][st] pilot [in] Lyl[at].>
	MSG	<chameleon OTHER Cap'n [Wo][lf] [ha]s [or]d[er][ed] [me] [to] cru[sh] [yo]u.>
	MSG	<pig OTHER [An][dr]o[ss] paid [me] [we][ll]. [Th][is] [wi][ll] [be] [an] e[as]y job!>
	MSG	<monkey OTHER Cap'n [Wo][lf] [to][ld] [me] [th]e [St][ar] [Fo]x te[am] w[as] [no][th][in]g!>
	MSG	<wolf OTHER W[or][th][le][ss] c[ow][ar]ds. Y[ou] a[ct] [to]ugh, but I'[ll] [de][st]roy [yo]u.>
	MSG	<pepper OTHER [Th]e [en][em]y's [ta]k[en] [th]e s[at]e[ll][it]e [pl][at][fo][rm]. [He]lp [us]!>
	MSG	<wolf OTHER My opp[on][en]ts [al]w[ay]s eva[po]r[at]e [in][to] [sp]a[ce] du[st]!>
	MSG	<chameleon OTHER Ho, ho! Y[ou] [ha][ve] [so][me] ski[ll]s, but I [wi][ll] [no]t lo[se]!>
	MSG	<pig OTHER Y[ou]'[re] [no]t [ba]d-  [fo]r [an] [am][at]e[ur]!>
	MSG	<monkey OTHER [Th][er]e [is] [no] safe [pl]a[ce] [fo]r [yo]u [no]w!>
	MSG	<wolf OTHER [He][ar] [me], [St][ar] [Fo]x! I, [St][ar] [Wo][lf], [wi][ll] [de]fe[at] [yo]u [no]w!>
	MSG	<FOX OTHER W[ay] [to] [go]! Y[ou] did [it], but I w[as] a b[it] w[or][ri][ed].>
	MSG	<FALCO OTHER I [go]t w[or][ri][ed], [an]d I w[an]t[ed] [to] [ta][ke] [yo][ur] [pl]a[ce].>
	MSG	<PEPPY OTHER A[re] [yo]u ok[ay]? N[ow] [th][at] w[as] a te[st] [of] [yo][ur] ski[ll]s!>
	MSG	<SLIPPY OTHER C[rr]roak! I [th][ou]ght [it] w[as] [al]l [ov][er] [fo]r a [mi]nute!>
	MSG	<GIRL1 OTHER Go[od] job! [Th][at] w[as] a nail-b[it][er]!>
	MSG	<GIRL2 OTHER Whew! [We] [al]mo[st] didn['t] [ge]t [ou]t [of] [th][at] scrape!>
	MSG	<FOX special It's [al]l [ri]ght! Y[ou] ju[st] [go]t[ta] [be]l[ie][ve]!>
	MSG	<FALCO special Y[ou] [sh][ou][ld]n['t] [ha][ve] wo[rr]i[ed], [it] w[as]n['t] [th][at] [to]ugh!>
	MSG	<PEPPY special H[ey], [it] w[as] [no] prob[le]m! P[ie][ce] [of] [ca][ke]!>
	MSG	<SLIPPY special Rr[ri][bb][it]! [Th][at]'s [ri]ght! I w[as] [ne]rvo[us], [to]o.>
	MSG	<GIRL1 special P[ar]d[on]? It w[as] e[as]y! R[em][em]b[er], I'[ve] [go]t ski[ll]s!>
	MSG	<GIRL2 special Wh[at]? It w[as]n['t] [al]l [th][at] [ba]d...[we] [to][as]t[ed] '[em]!>
	MSG	<pepper OTHER [Yo][ur] Mo[th][er][sh][ip]. U[se] [th]e [sh][ip] [to] p[ow][er] [up] [sh][ie][ld]s [an]d w[ar]p.>
	MSG	<pepper down [Th]e s[at]e[ll][it]e [is] [at][ta][ck][in]g [Co][rn][er][ia]. Re[ca]p[tu][re] [it]!>
	MSG	<pepper OTHER [Th]e [de]f[en][se] sy[st][em] [de][st]roy[ed] [an] [en][em]y t[ar]g[et].>
	MSG	<FOX OTHER Qui[ck][ly] p[re][ss] [(L)] [or] [(R)] t[wi][ce] [to] avoid [en][em]y [sh]ots.>
	MSG	<FALCO OTHER P[re][ss] [(L)] [or] [(R)] t[wi][ce], [an]d [yo]u c[an] avoid [sh]ots.>
	MSG	<PEPPY OTHER Qui[ck][ly] [ta]p [(L)] [or] [(R)] t[wi][ce] [to] avoid [en][em]y [sh]ots.>
	MSG	<SLIPPY OTHER [To] ro[ll] [an]d avoid [en][em]y [sh]ots, [ta]p [(L)] [or] [(R)] t[wi][ce].>
	MSG	<GIRL1 OTHER Tap [(L)] [or] [(R)] t[wi][ce] [to] ro[ll] [an]d [do]d[ge] [en][em]y [sh]ots.>
	MSG	<GIRL2 OTHER [To] avoid [en][em]y [sh]ots, qui[ck][ly] [ta]p [(L)] [or] [(R)] t[wi][ce].>
	MSG	<pepper OTHER L[et] [me] te[ll] [yo]u h[ow] [to] c[on][tr]ol a W[al]k[in]g craft.>
	MSG	<pepper OTHER U[se] [DPAD] [to] c[on][tr]ol [th]e di[re][ct]i[on], [an]d [(L)] [an]d [(R)] [to] [sp][in].>
	MSG	<pepper OTHER [To] mo[ve] [fa][st][er], [ta]p [DPAD] t[wi][ce] [in] [an]y di[re][ct]i[on].>
	MSG	<pepper OTHER U[se] [(Y)] [to] jump. P[re][ss] [(SE][NOSP][LE][NOSP][CT)] [to] [tr][an]s[fo][rm].>
	MSG	<pepper OTHER Ma[ke] [go][od] u[se] [of] [th]e [tr][an]s[fo][rm][in]g [ca]pabili[ti]es.>
	MSG	<pepper help [Th]e s[at]e[ll]ite [ha]s [be][en] [ov][er]r[un]. Ta[ke] [it] [ba][ck]!>
	MSG	<pepper OTHER F[in][al][ly], [An][dr]o[ss]'s [fo]r[ce]s [in] [th]e Lyl[at] sy[st][em] [ar]e [de]fe[at][ed]!>
	MSG	<pepper OTHER P[re][ss] [on]! Y[ou] [mu][st] [ne]u[tr][al]ize [An][dr]o[ss] [on][ce] [an]d [fo]r [al]l!>
	MSG	<pepper OTHER Sw[it][ch] [po]s[it]i[on]s [wi][th] [yo][ur] [wi]ng [ma]n [by] p[re][ss][in]g [(SE][NOSP][LE][NOSP][CT)].>
	MSG	<pepper OTHER U[se] [(B)] [to] jump, [an]d p[re][ss] [(SE][NOSP][LE][NOSP][CT)] [to] [tr][an]s[fo][rm].>
	MSG	<pepper OTHER Bl[as]t[er] le[ve]l [no]w ra[is][ed]. H[om][in]g [sh]ots [en]abl[ed]!>
	MSG	<pepper OTHER Pla[ce] [th]e [ta]rg[et] m[ar]k[er] [on] [an] [en][em]y [an]d [fi]re!>
	MSG	<pepper OTHER [Yo]u'[ve] loc[at][ed] a [se]cr[et] [ba][se]! Try [to] [ga][in] [en][tr][an][ce].>
