	MSG	<pepper OTHER スタ-フォックスのしょくん きこえているか? 大変なことになったそﾞ!!>
	MSG	<pepper OTHER あの アントﾞルフかﾞ 生きておったのたﾞ!>
	MSG	<pepper OTHER そして, わかﾞコ-ネリアに たいして 攻撃をしかけて きたのたﾞ!>
	MSG	<pepper OTHER アントﾞルフ軍の大型空母と 空母から出撃した 攻撃部隊かﾞ>
	MSG	<pepper OTHER コ-ネリアに向かって 移動中たﾞ。>
	MSG	<pepper OTHER さらに, ライラット系の いくつかの惑星には, アントﾞルフ軍の基地かﾞ>
	MSG	<pepper OTHER つくられ, コ-ネリアに向け 惑星間ミサイルかﾞ 発射されはしﾞめた。>
	MSG	<pepper OTHER この戦いには やはり きみたちのたすけかﾞ ひつようたﾞ。>
	MSG	<pepper OTHER コ-ネリアも, 少しくらいの タﾞメ-シﾞなら もちこたえる こともてﾞきるかﾞ, もしも>
	MSG	<pepper OTHER タﾞメ-シﾞかﾞ 100%に なってしまうと, 全てかﾞおしまいたﾞ!>
	MSG	<pepper OTHER コ-ネリアの被害を てﾞきるたﾞけおさえ,>
	MSG	<pepper OTHER アントﾞルフ軍を全滅に おいこむのたﾞ。  たのむそﾞ スタ-フォックス!!!>
	MSG	<pepper OTHER アントﾞルフ軍の基地に 侵入し, 内部から 基地を破壞してくれ。>
	MSG	<pepper OTHER 敵の空母に侵入し 内部から破壞して 撃沈するのたﾞ。>
	MSG	<pepper down コ-ネリアかﾞ攻撃を 受けておる。>
	MSG	<pepper down コ-ネリアかﾞ攻撃されて いるそﾞ! なんとかならんのか!!>
	MSG	<pepper DOWN コ-ネリアかﾞ攻撃されて いる! もう あとかﾞない! はやく 来てくれ!!!>
	MSG	<pepper down コ-ネリアかﾞミサイルてﾞ 被害を受けた なにをしているんたﾞ!!>
	MSG	<pepper down コ-ネリアかﾞ フﾟラネット キャノンの攻撃てﾞ タﾞメ-シﾞを受けた!>
	MSG	<pepper OTHER 惑星に とうちゃくするか, 敵に せっきんすると 戦いに入ります。>
	MSG	<pepper OTHER マサﾞ-シッフﾟにもとﾞると 敵基地のない惑星に  ワ-フﾟてﾞきます。>
	MSG	<pepper OTHER カ-ソルを動かし, [(B)]てﾞ ア-ウィンの 移動先を 決めてくたﾞさい。>
	MSG	<ANDROSS OTHER 私は 復活した! コ-ネリアへのふくしゅうを はたすために・・・>
	MSG	<ANDROSS HELP コ-ネリアのやつらめ おもいしるかﾞよい!>
	MSG	<ANDROSS DOWN この宇宙てﾞ, もっとも いたﾞいなものかﾞ たﾞれなのかということを!>
	MSG	<FOX OTHER [(Y)]てﾞ フﾞ-ストを 使えるせﾞ! おほﾞえておけよ!>
	MSG	<FALCO OTHER ア-ウィンのフﾞ-ストは [(Y)]ホﾞタンたﾞ! 加速てﾞきるせﾞ!>
	MSG	<PEPPY OTHER [(Y)]を押している間, フﾞ-ストてﾞ加速 てﾞきるそﾞ!>
	MSG	<SLIPPY OTHER [(Y)]を押している間 フﾞ-ストを使って 速くとふﾞケロ!>
	MSG	<GIRL1 OTHER 加速したかったら [(Y)]を押している間 フﾞ-ストするわよ!>
	MSG	<GIRL2 OTHER [(Y)]を押している間 フﾞ-ストして 速く とへﾞるわ!>
	MSG	<FOX OTHER [(Y)]ホﾞタンのフﾞ-ストてﾞ ついせきするんたﾞ!>
	MSG	<FALCO OTHER トロトロすんな! [(Y)]フﾞ-ストを使うんたﾞ>
	MSG	<PEPPY OTHER たﾞいふﾞとおくにいるそﾞ [(Y)]のフﾞ-ストを使え!>
	MSG	<SLIPPY OTHER あんなに向こうたﾞケロ! [(Y)]フﾞ-ストてﾞ加速たﾞ!>
	MSG	<GIRL1 OTHER たﾞいふﾞ向こうにいるわ! [(Y)]フﾞ-ストてﾞ おいかけるのよ!>
	MSG	<GIRL2 OTHER [(Y)]のフﾞ-ストを使って おいかけないと にけﾞられちゃうわ!!>
	MSG	<FOX OTHER コ-ネリアかﾞあふﾞない! [(ST][NOSP][AR][NOSP][T)]てﾞ ここから はなれよう!>
	MSG	<FALCO OTHER ちっ! しかたねぇ [(ST][NOSP][AR][NOSP][T)]てﾞ たすけに いこうせﾞ!>
	MSG	<PEPPY OTHER コ-ネリアに向かおう! [(ST][NOSP][AR][NOSP][T)]てﾞ ここを ぬけるんたﾞ!>
	MSG	<SLIPPY OTHER コ-ネリアかﾞやられたら 大変たﾞ! [(ST][NOSP][AR][NOSP][T)]てﾞ もとﾞろうよ!>
	MSG	<GIRL1 OTHER まぁ! 大変たﾞわ! [(ST][NOSP][AR][NOSP][T)]てﾞ ここから はなれましょう!>
	MSG	<GIRL2 OTHER あら, こまったわねぇ・・・ [(ST][NOSP][AR][NOSP][T)]てﾞ もとﾞりましよう!>
	MSG	<FOX OTHER もう 時間かﾞないそﾞ! [(ST][NOSP][AR][NOSP][T)]てﾞ ここは あきらめるんたﾞ!>
	MSG	<FALCO OTHER ましﾞてﾞ ヤハﾞイせﾞ!! [(ST][NOSP][AR][NOSP][T)]てﾞ ここを ぬけようせﾞ!>
	MSG	<PEPPY OTHER もう たﾞめたﾞ!! [(ST][NOSP][AR][NOSP][T)]てﾞ ひとますﾞ もとﾞろう!>
	MSG	<SLIPPY OTHER 大ヒﾟンチ!! すくﾞに [(ST][NOSP][AR][NOSP][T)]てﾞいかないと アウトたﾞ〜!>
	MSG	<GIRL1 OTHER ひとますﾞここは, あきらめましょう! [(ST][NOSP][AR][NOSP][T)]を押して!>
	MSG	<GIRL2 OTHER タイムリミットよ! 今, [(ST][NOSP][AR][NOSP][T)]てﾞ向かわ ないと おしまいよ!>
	MSG	<FOX OTHER 作戦エリアから はすﾞれている。 もとﾞるそﾞ, ついて来い!>
	MSG	<FALCO OTHER せわかﾞやけるせﾞ! 作戦エリアはこっちたﾞ ついて来な !!>
	MSG	<PEPPY OTHER お〜い とﾞうした? ここにはなにもないそﾞ! ついて来るんたﾞ!!>
	MSG	<SLIPPY OTHER ケロ〜! みちにまよった みたいたﾞケロ。 たふﾞん こっちたﾞとおもうケロ !>
	MSG	<GIRL1 OTHER あらあら, せわかﾞやける ひとねぇ。 もとﾞるわよ ! ついてらっしゃい !!>
	MSG	<GIRL2 OTHER ねぇ, このへんには なにもないわ。 あっちに いってみましょうよ・・・>
	MSG	<FOX OTHER [(SE][NOSP][LE][NOSP][CT)]てﾞ 変型てﾞきるせﾞ。 おほﾞえておけよ !>
	MSG	<FALCO OTHER ア-ウィンの変型は [(SE][NOSP][LE][NOSP][CT)]たﾞ! わすれんしﾞゃね-そﾞ!>
	MSG	<PEPPY OTHER [(SE][NOSP][LE][NOSP][CT)]を押せはﾞ 変型てﾞきるそﾞ。>
	MSG	<SLIPPY OTHER ア-ウィンの変型は [(SE][NOSP][LE][NOSP][CT)]たﾞよ。 わすれないてﾞケロ〜!>
	MSG	<GIRL1 OTHER 変型したくなったら [(SE][NOSP][LE][NOSP][CT)]を 押すのよ !>
	MSG	<GIRL2 OTHER [(SE][NOSP][LE][NOSP][CT)]を押したら ア-ウィンは変型するわ !>
	MSG	<FOX OTHER きをつけろ! マクﾞマの上におりたら タﾞメ-シﾞを受けるそﾞ!>
	MSG	<FALCO OTHER へい! マクﾞマの上に おりるなよ! やけとﾞしてもしらね-せﾞ>
	MSG	<PEPPY OTHER マクﾞマにちゃくちすると タﾞメ-シﾞを受けるそﾞ きをつけろよ!>
	MSG	<SLIPPY OTHER あつ〜い あつ〜い カラタﾞかﾞカラカラたﾞ〜 あつ〜い あつ〜い !!!>
	MSG	<GIRL1 OTHER マクﾞマの上におりたら タﾞメ-シﾞを受けちゃうわ しんちょうにね!>
	MSG	<GIRL2 OTHER きをつけて! うっかり おりたら タﾞメ-シﾞを 受けるわよ!>
	MSG	<FOX OTHER そとからの攻撃てﾞは タﾞメたﾞ! 入ロを開く スイッチを さかﾞせ!>
	MSG	<FALCO OTHER ちょくせつ攻撃は むたﾞ! 入ロを開くスイッチを さかﾞすんたﾞ!!>
	MSG	<PEPPY OTHER 攻撃はきかないそﾞ! 中に入るための しかけを さかﾞすんたﾞ!!>
	MSG	<SLIPPY OTHER 攻撃はきかないケロ! 入ロのスイッチを さかﾞすんたﾞケロ!!>
	MSG	<GIRL1 OTHER そとからの攻撃には ひﾞくともしないわ! 入ロを開かなきゃ!!>
	MSG	<GIRL2 OTHER とﾞこかに 入ロを開く   スイッチかﾞ   あるはすﾞよ!!>
	MSG	<FOX OTHER ハﾞリアかﾞはってあって ちかつﾞけないそﾞ! 発生そうちを壞せ!!>
	MSG	<FALCO OTHER ハﾞリア発生そうちを 破壞しないと ちかつﾞけね-せﾞ!!>
	MSG	<PEPPY OTHER ハﾞリアかﾞあるそﾞ! ますﾞ, 発生そうちを 破壞しないと・・・>
	MSG	<SLIPPY OTHER 基地のまわりにあるのかﾞ ハﾞリア発生そうちたﾞ 壞しちゃえケロ!>
	MSG	<GIRL1 OTHER ハﾞリアをきらないと ちかつﾞけないわ! なんとかしなきゃ!!>
	MSG	<GIRL2 OTHER ハﾞリアかﾞはってあるわ! 発生そうちを 壞すのよ!>
	MSG	<pepper help 敵の空母から あらたな 攻撃部隊かﾞ 出撃したそﾞ!!>
	MSG	<pepper help 惑星間ミサイルかﾞ コ-ネリアに向けて 発射されたそﾞ!!>
	MSG	<pepper help 大変たﾞ! あらたな 敵の空母かﾞ あらわれたそﾞ!!>
	MSG	<pepper OTHER コ-ネリアのタﾞメ-シﾞに ちゅういしてくたﾞさい。>
	MSG	<FOX OTHER >
	MSG	<andross OTHER えんりょは いらんそﾞ やつらを おもいきり いためつけてやるのたﾞ!!>
	MSG	<pepper OTHER よくやった。 これてﾞ この惑星からのミサイル 攻撃は なくなるたﾞろう。>
	MSG	<ANDROSS HELP おのれ スタ-フォックス・・・ またしても 私のしﾞゃまを しようというのか・・・>
	MSG	<ANDROSS DOWN クﾞォ〜! とﾞいつもこいつも なにをやっておるのたﾞ〜! やくにたたぬやつらめ〜!!>
	MSG	<pepper OTHER よくやった! これてﾞ コ-ネリアへの攻撃も たﾞいふﾞ よわまるそﾞ。>
	MSG	<FOX OTHER ハﾟ-トナ-てﾞ コンティニュ-しますか?>
	MSG	<FOX OTHER はい>
	MSG	<FOX OTHER いいえ>
	MSG	<pepper OTHER コ-ネリアを守っている サテライト・システムたﾞ。>
	MSG	<pepper OTHER サテライト・システムかﾞ 敵に せんきょされてしまった! とりかえしてくれ!!>
	MSG	<FOX OTHER MISSION>
	MSG	<FOX OTHER RECORD>
	MSG	<FOX OTHER TEST>
	MSG	<FOX OTHER TRAINING>
	MSG	<FOX OTHER CONFIG>
	MSG	<FOX OTHER STEREO>
	MSG	<FOX OTHER MONO>
	MSG	<FOX OTHER NORMAL>
	MSG	<FOX OTHER HARD>
	MSG	<FOX OTHER EXPERT>
	MSG	<FOX OTHER マサﾞ-シッフﾟてﾞ移動 しますか?        はい                  [NOSP]いいえ>
	MSG	<FOX OTHER カ-ソルを動かし, [(B)]てﾞ マサﾞ-シッフﾟの移動先を 決めてくたﾞさい。>
	MSG	<pepper OTHER サテライト・システムを とりかえすことかﾞ てﾞきた。 こﾞくろう!>
	MSG	<FOX OTHER [RARR]>
	MSG	<pepper OTHER マサﾞ-シッフﾟに もとﾞると ア-ウィンのシ-ルトﾞを 回復てﾞきます。>
	MSG	<pepper DOWN クﾞァ〜〜〜!!! もうおしまいたﾞ〜! コ-ネリアかﾞ壞滅たﾞ〜!!>
	MSG	<ANDROSS OTHER なにやら ねすﾞみかﾞ ちょろちょろしておるようたﾞ おもしろい・・・>
	MSG	<ANDROSS HELP いって あそんてﾞやれ! てかけﾞんしてやるの たﾞそﾞ! カﾞハハハ!!>
	MSG	<ANDROSS OTHER カﾞハハハハ!! 少しくらい はこﾞたえかﾞ ないと つまらんからな!>
	MSG	<ANDROSS DOWN コ-ネリアへ向け 惑星間ミサイル発射たﾞ!>
	MSG	<ANDROSS HELP フﾟラネット・キャノンの 射程内に コ-ネリアを とらえたそﾞ! カﾞハハ!>
	MSG	<ANDROSS DOWN これてﾞも くらえ! フﾟラネット・キャノン発射!!!>
	MSG	<ANDROSS OTHER フン なかなかやるわい たﾞかﾞ戦いは これからたﾞ!!>
	MSG	<ANDROSS HELP フォッ フォッ それくらいてﾞ いいきになっているとは おめてﾞたいやつらよ・・・>
	MSG	<ANDROSS DOWN あそひﾞは ここまてﾞたﾞ ゆけ! そして やつらを ひねりつふﾞすのたﾞ!!>
	MSG	<ANDROSS DOWN ここまてﾞやるとは たいした ものたﾞ! これは たのしませ てくれた おれいたﾞ!>
	MSG	<ANDROSS HELP 攻撃空母! 全速てﾞ コ-ネリアへ向かえ! フﾟラネット・キャノンようい!!>
	MSG	<FOX OTHER [(X)]てﾞ フﾞ-ストを 使えるせﾞ! おほﾞえておけよ!>
	MSG	<FALCO OTHER ア-ウィンのフﾞ-ストは [(X)]ホﾞタンたﾞ! 加速てﾞきるせﾞ!>
	MSG	<PEPPY OTHER [(X)]を押している間, フﾞ-ストてﾞ加速 てﾞきるそﾞ!>
	MSG	<SLIPPY OTHER [(X)]を押している間 フﾞ-ストを使って 速くとふﾞケロ!>
	MSG	<GIRL1 OTHER 加速したかったら [(X)]を押している間 フﾞ-ストするわよ!>
	MSG	<GIRL2 OTHER [(X)]を押している間 フﾞ-ストして 速く とへﾞるわ!>
	MSG	<FOX OTHER [(X)]ホﾞタンのフﾞ-ストてﾞ ついせきするんたﾞ!>
	MSG	<FALCO OTHER モタモタすんな! [(X)]フﾞ-ストを使うんたﾞ>
	MSG	<PEPPY OTHER たﾞいふﾞとおくにいるそﾞ [(X)]のフﾞ-ストを使え!>
	MSG	<SLIPPY OTHER あんなに向こうたﾞケロ! [(X)]フﾞ-ストてﾞ加速たﾞ!>
	MSG	<GIRL1 OTHER たﾞいふﾞ向こうにいるわ! [(X)]フﾞ-ストてﾞ おいかけるのよ!>
	MSG	<GIRL2 OTHER [(X)]のフﾞ-ストを使って おいかけないと!!>
	MSG	<ANDROSS OTHER クﾞクﾞクﾞ・・・ 私を ほんきにさせるとは・・・ ほねのあるやつらたﾞ!!>
	MSG	<pepper HELP フﾟラネット・キャノンへの エネルキﾞ-・チャ-シﾞを キャッチ! 敵空母へ向え!>
	MSG	<pepper OTHER フﾟラネット・キャノンに エネルキﾞ-をチャ-シﾞ中たﾞ 発射まえに撃沈するんたﾞ!!>
	MSG	<ANDROSS OTHER みこﾞとな おてなみたﾞな スタ-フォックス!>
	MSG	<ANDROSS OTHER うてﾞをあけﾞたな スタ-フォックス>
	MSG	<ANDROSS OTHER ついに ここまてﾞ やってきたか! まちかねたそﾞ>
	MSG	<ANDROSS HELP たいしたものたﾞ! たﾞかﾞ きさまらの いのちも ここまてﾞたﾞ!>
	MSG	<ANDROSS HELP きさまなとﾞ しょせんは ヘﾟハﾟ-に 使われる あやつりにんきﾞょうよ>
	MSG	<ANDROSS HELP なんとﾞも なんとﾞも しﾞゃまをしおって! コ-ネリアの いぬめ!!>
	MSG	<ANDROSS DOWN すくﾞに らくにして やるそﾞ ありかﾞたく おもうかﾞよい!!>
	MSG	<ANDROSS DOWN あの時のうらみ けっしてわすれはしない! かくこﾞするかﾞいい!!>
	MSG	<ANDROSS DOWN たっふﾟり かわいかﾞって くれるわ! ほえすﾞらかくな!!>
	MSG	<FOX OTHER クッ・・・ ミサイルかﾞ おちはしﾞめたそﾞ! いそいてﾞ破壞するんたﾞ>
	MSG	<FALCO OTHER ヤロ-! ミサイルかﾞ おちはしﾞめやかﾞった! いそかﾞね-と!>
	MSG	<PEPPY OTHER ますﾞい! ミサイルかﾞ コ-ネリアに おちはしﾞめたそﾞ!!>
	MSG	<SLIPPY OTHER ケﾞロ〜ッ ミサイルかﾞ コ-ネリアに おっこちはしﾞめたケロ〜!>
	MSG	<GIRL1 OTHER キャ-ッ! コ-ネリアに ミサイルかﾞおちていくわ! いそいてﾞ破壞しなきゃ!>
	MSG	<GIRL2 OTHER 大変よ! ミサイルかﾞ おちはしﾞめちゃったわ! はやく射ちおとすのよ!>
	MSG	<FOX OTHER これてﾞ この惑星からは ミサイルは 発射されなく なるそﾞ!!>
	MSG	<FALCO OTHER へん! アントﾞルフの基地 なんさﾞ めしﾞゃね-せﾞ!>
	MSG	<PEPPY OTHER よっしゃ! これてﾞこの星 からの ミサイル攻撃を ふうしﾞこめたそﾞ!!>
	MSG	<SLIPPY OTHER やった〜 基地を壞したし この星からは,ミサイルてﾞ 攻撃てﾞきないよ〜タﾞ!>
	MSG	<GIRL1 OTHER やったわ! アントﾞルフの 基地なんか たいしたこと ないわよネッ!>
	MSG	<GIRL2 OTHER 基地かﾞなけれはﾞ この星から ミサイルは 射ちあけﾞられないわネ!>
	MSG	<FOX OTHER オ-ケ-! こいつを たたいておけはﾞ 戦いは たﾞいふﾞらくになるせﾞ!>
	MSG	<FALCO OTHER てﾞかいはﾞっかてﾞ ちっとも はこﾞたえかﾞ ないせﾞ!>
	MSG	<PEPPY OTHER これてﾞ敵の攻撃部隊も すこしは かすﾞかﾞ へるたﾞろう!>
	MSG	<SLIPPY OTHER アントﾞルフの空母なんか チョロイんたﾞな! らくしょうたﾞケロ!!>
	MSG	<GIRL1 OTHER 空母を沈めれはﾞ 中の 攻撃部隊もいっしょに こっはﾟみしﾞんね!>
	MSG	<GIRL2 OTHER 空母をたたいておけはﾞ 攻撃部隊もへるし たﾞいふﾞ らくになるわ!>
	MSG	<wolf DOWN ヌォ-ッ!!  さすかﾞは スタ-フォックス! これほとﾞの うてﾞとは・・・>
	MSG	<chameleon DOWN キﾞェ〜ッ! ウルフ親分, あとは たのみましたせﾞ!>
	MSG	<pig DOWN こっ こんなやろうに・・・!! わしも やきかﾞまわった もんしﾞゃ〜!!>
	MSG	<monkey DOWN キィ〜ッ! くやし〜!! おほﾞえてやかﾞれ〜!! ちきしょ〜!!>
	MSG	<wolf DOWN 今日のところは俺の 負けたﾞ・・・。 このかりは, 必すﾞかえすそﾞ!!>
	MSG	<chameleon OTHER おっと! そこまてﾞたﾞ! スタ-ウルフのレオン たたﾞ今 参上!!!>
	MSG	<pig OTHER またんか われ〜! スタ-ウルフのヒﾟクﾞマ 参上! かくこﾞせいや!!!>
	MSG	<monkey OTHER アルシﾞ-さまの お出ましたﾞ-! かってな まねは, させね-そﾞ!!>
	MSG	<wolf OTHER ヘﾟハﾟ-にのせられて いいきになりやかﾞって! いけすかねぇやろうたﾞ!!>
	MSG	<chameleon OTHER ウルフ親分かﾞ受けた しこﾞとなんてﾞな・・・ ここてﾞきえてもらうせﾞ!>
	MSG	<pig OTHER アントﾞルフから たんまり もらったかﾞ かんたんな しこﾞとしﾞゃの〜!!>
	MSG	<monkey OTHER スタ-フォックスのやつら なんか めしﾞゃね-って 親分かﾞ いってたそﾞ-!!>
	MSG	<wolf OTHER ひよっこかﾞ いきかﾞって やかﾞると とﾞうなるか たっふﾟり おしえてやる!!>
	MSG	<pepper OTHER サテライト・システムかﾞ 敵のてにおちた! すくﾞに とりもとﾞすんたﾞ!!>
	MSG	<wolf OTHER しょうはﾞいかﾞたきには このへんてﾞ きえてもらおうか!!>
	MSG	<chameleon OTHER キﾞキﾞキﾞ!      やるな スタ-フォックス!! しかし 負けんそﾞ!!!>
	MSG	<pig OTHER なかなかやるの〜 たﾞかﾞ しょせんは おこさまレヘﾞルなんしﾞゃ>
	MSG	<monkey OTHER こんなことして おまえ たたﾞてﾞすむと おもうなよ〜! キ〜〜!!>
	MSG	<wolf OTHER まちな! スタ-フォックス!! ここから先へは このウルフかﾞ いかせねぇせﾞ>
	MSG	<FOX OTHER やったな! てﾞも なかなか 出て来ないから しんはﾟいしたせﾞ!!>
	MSG	<FALCO OTHER フン! しんはﾟいさせやかﾞって 俺かﾞいけはﾞよかったせﾞ>
	MSG	<PEPPY OTHER たﾞいしﾞょうふﾞか? もう少してﾞ いっしょに おちるところたﾞったそﾞ!>
	MSG	<SLIPPY OTHER ケロ〜! いっしょに やられちゃうかと ハラハラしちゃったケロ!>
	MSG	<GIRL1 OTHER やったね! てﾞも とﾞうなっちゃうのかと おもったわよ!>
	MSG	<GIRL2 OTHER フ-ッ! ふﾞしﾞに たﾞっしゅつしたみたいね よかったわ!>
	MSG	<FOX special たﾞいしﾞょうふﾞ! 俺のうてﾞを しんしﾞろって!!>
	MSG	<FALCO special フン! なまいきなこと いってんしﾞゃねぇよ! らくしょうたﾞせﾞ!!>
	MSG	<PEPPY special しんはﾟい こﾞむよう! このとうり ノ-フﾟロフﾞレムたﾞ!!>
	MSG	<SLIPPY special そうケロ! ホﾞクも しﾞふﾞんてﾞ トﾞキトﾞキしちゃった!!>
	MSG	<GIRL1 special な〜にいってんの! 私をたﾞれたﾞと おもってんのよ!!>
	MSG	<GIRL2 special あら? こんなこと せﾞ〜んせﾞんへいきよ! よゆうあったもの!!>
	MSG	<pepper OTHER マサﾞ-シッフﾟたﾞ。 ア-ウィンのシ-ルトﾞ回復や 惑星間ワ-フﾟかﾞてﾞきる。>
	MSG	<pepper down サテライト・システムかﾞ コ-ネリアを攻撃してきた! はやく とりかえしてくれ!>
	MSG	<pepper OTHER あんしんしたまえ, サテライト・システムかﾞ 敵を射ちおとした。>
	MSG	<FOX OTHER [(L)]か[(R)]を すはﾞやく2回 押すと ロ-リンクﾞてﾞ 敵の攻撃をはしﾞくせﾞ!>
	MSG	<FALCO OTHER [(L)]か[(R)]を すはﾞやく2回 押すと ロ-リンクﾞして 敵の攻撃をはしﾞくせﾞ!>
	MSG	<PEPPY OTHER すはﾞやく2回 [(L)]か[(R)]を 押すんたﾞ! 敵の攻撃を はしﾞけるそﾞ>
	MSG	<SLIPPY OTHER すはﾞやく2回 [(L)]か[(R)]を 押せはﾞ 敵の攻撃を はしﾞいちゃうケロ!!>
	MSG	<GIRL1 OTHER [(L)]か[(R)]を すはﾞやく2回 押せはﾞ ロ-リンクﾞして 敵の攻撃を はしﾞくわ!>
	MSG	<GIRL2 OTHER [(L)]か[(R)]を すはﾞやく2回 押すと ロ-リンクﾞして 敵の攻撃を はしﾞくわ!>
	MSG	<pepper OTHER ねんのため ウォ-カ-の コントロ-ルについて せつめい しておこう。>
	MSG	<pepper OTHER [DPAD]てﾞ前後左右に移動し [(L)][(R)]てﾞウォ-カ-の 向きを変えるのたﾞ。>
	MSG	<pepper OTHER 速く移動したい時は [DPAD]を押しつつﾞけると 加速して はしるそﾞ。>
	MSG	<pepper OTHER シﾞャンフﾟは[(A)]たﾞ。 そして[(SE][NOSP][LE][NOSP][CT)]を押せはﾞ変型てﾞきる。>
	MSG	<pepper OTHER ア-ウィンの変型を うまく使うのたﾞそﾞ!>
	MSG	<pepper help サテライト・システムかﾞ 敵にうはﾞわれた! すくﾞに 向ってくれ!!>
	MSG	<pepper OTHER これてﾞ ライラット系内の アントﾞルフ軍は いっそうされた。>
	MSG	<pepper OTHER このまま いっきに アントﾞルフを たたいてしまうのたﾞ!!>
	MSG	<pepper OTHER [(SE][NOSP][LE][NOSP][CT)]を押すと ハﾟ-トナ-と こうたいてﾞきます。>
	MSG	<pepper OTHER シﾞャンフﾟは[(B)]たﾞ。 そして[(SE][NOSP][LE][NOSP][CT)]を押せはﾞ変型てﾞきる。>
	MSG	<pepper OTHER ハﾟワ-フﾞラスタ-かﾞ レヘﾞル・アッフﾟして  ホ-ミンクﾞするそﾞ。>
	MSG	<pepper OTHER タ-ケﾞットマ-カ-てﾞ ロック・オンして 発射するのたﾞ!!>
	MSG	<pepper OTHER シ-クレット・コロニ-たﾞ。 入ってみたまえ。>
